---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  interval: 5m
  chart:
    spec:
      chart: rook-ceph
      version: v1.8.1
      sourceRef:
        kind: HelmRepository
        name: rook-ceph-charts
        namespace: flux-system
  values:
    crds:
      enabled: false
    csi:
      enableCephfsDriver: false
      enableCephfsSnapshotter: false
    resources:
      requests:
        cpu: 100m
        memory: 128Mi