---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uptime-kuma-v1
  namespace: dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: longhorn
