apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
# CLOUDFLARE_EMAIL: The email used to log into https://dash.cloudflare.com
# CLOUDFLARE_APIKEY: Top right corner, "My profile" > "Global API Key"
# CLOUDFLARE_ZONEID: Can be found in the "Overview" tab of your domain
# CLOUDFLARE_RECORD_NAME: The name of your A record
stringData:
    cf_user: ENC[AES256_GCM,data:+hvuwfn4emMTmaTVJA/CtxYk,iv:hgYoWXT2oMYCzoI/JRp0bH6WhP8jMPxT6Et0MWnfHfQ=,tag:vO8DG0scIZ6qogSFlh2brA==,type:str]
    cf_apikey: ENC[AES256_GCM,data:iJaandtY06iVXM5OJF/2Ikcd5908g1uKIwrfBPgKEQMaNrs5Nw==,iv:7ndH+ZxGy5CU555tDEzH2t8Fgo/I/VeNwbh20/Mdx0c=,tag:fRj7liw+Ix6AiWDdt7SwBQ==,type:str]
    cf_zone: ENC[AES256_GCM,data:0z4njCK/UnZVYKBTMEsHdjNDa7SDoHlVI3KyXKjB6hU=,iv:3ClahEBocb3mH7uoNGB94iCApbV79R5YpvP+LIOTGFQ=,tag:778YEljFZsAoZbOidNkwJg==,type:str]
    cf_record_type: ENC[AES256_GCM,data:JA==,iv:s2dYQ4pUcMgC/rnn+9iF7hfw6aMBaanUaCAVoNRqw1A=,tag:cfTScXczuke95nYJ7l8UTQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pqmv9umk70z2xyv8vvlma070d9rzr02j3ye8gjyv64ddf0sfwccspwsj8d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMbTVqMWt5UHRoR0hlUGFI
            dCtOY0lSS21abkZKT1BndzA0TVNFWUszTG40CmNSZE1zeG43L2wxc1RKVXArMkw2
            Sm9FL20zUm15T1F1WnA2QkYyc3M5Qk0KLS0tIGt6OEIzdlYyUXkzc3p1cGEvQWhU
            MGZZZTBBcnF0Mmo1TWRmQUVMRTQvdFkKyhkRqddK5Y6YnaCIjueCqm3XNqHA/JGU
            29xKuBJ6c0xTzjgDwD3Buh9FSzt/lAZq8IV0wv9DICJ1ogLCBUimjw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-13T02:58:20Z"
    mac: ENC[AES256_GCM,data:sranA1Uv/RUJ5H4MH0O0nTQR/e+B3fiydjGFf5YNWkTxEH8ep9MJp3mfDIpVcsAJnOzy8kVJwWs3OMrjbtvrJGMdeq6pTeuW7+9vxNNlIKixvH2qzZWcZ8qPZaK2xO0xQ9FmyyrZC8ON2tUN9jFsF8E7o3k/TGIzqCWnsqd/MPo=,iv:3ToMsc7gjaQ0Op7hSviAGUezJwELEyUTGBBVN+V7ePM=,tag:yjZnLgZVjrB1wplLpTZjYw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
