apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
# CLOUDFLARE_EMAIL: The email used to log into https://dash.cloudflare.com
# CLOUDFLARE_APIKEY: Top right corner, "My profile" > "Global API Key"
# CLOUDFLARE_ZONEID: Can be found in the "Overview" tab of your domain
# CLOUDFLARE_RECORD_NAME: The name of your A record
stringData:
    cf_user: ENC[AES256_GCM,data:goa7zjjmbYI1RF7OgcycOZZ0,iv:nfJRo2z37a7V8ir6QbWNLZrelMHOl2wESh2/0K3dnzI=,tag:01uTNv4DDcOLSmnSZLcFAQ==,type:str]
    cf_apikey: ENC[AES256_GCM,data:amhnHY6Tb2pmqkNceGv+brZbrukV9renBO/SdCGwrM1bgBk2ew==,iv:K7O0ZlQWceorpr3DIOjTV24rpcTgxeE3zuejKuqI8Cw=,tag:/GT/E/SaDfYRuIav1aVioA==,type:str]
    cf_zone: ENC[AES256_GCM,data:HyZsT7wT/SVYj9WafeNjq8q/oN8waup2xqGb+BelEEM=,iv:bDgeqLeZxQI/r8mMAPin9zDvG+CZUcXJFpB5RBKnaEI=,tag:tl2xTZugVgoXXocyyErN/A==,type:str]
    cf_record_type: ENC[AES256_GCM,data:E05k1DdLRy4POIc=,iv:TmSjW34I9GUT2Ebu0NUOaHCLKpBolWiXT4s9/xu/prQ=,tag:qc5FCyYnw+2lydC6Rg1J6A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pqmv9umk70z2xyv8vvlma070d9rzr02j3ye8gjyv64ddf0sfwccspwsj8d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaOG1ER1Y0SVFlaWtmMEFt
            VGUyNzduR3IrcExuM3NjbUg5aXhzNnprYVZvCmFIcXZwRzgrbzBNZ3NxS2dvZ2xT
            ODVYNmwycWRMVTlKcWpObVVOZStRL0UKLS0tIEVjck4rL2FrUTNxNnhERU9SU3lV
            YU15N3BNSzlpd2pUNUxIdWtsTGhVdTAK6qESvOxrEqrgFNwrd96heY/vlcwlHKIB
            P2Tysw7a7tHn/OKHX1mKyuP2S0uwVOCSWPaZY+S2N0nf3DdHqPYMEQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-13T13:07:08Z"
    mac: ENC[AES256_GCM,data:gBfh/6wRRezQO3WZbSR94oPWNjZSSbkikxZmQN8XMqfW28khV7mt08PO2o4ytKy8ZgZ83U3XxmGQM/AVw+NF/Pcr3qb/t3EVY8ciDmFD299fK+qbJSInczHmdG5mkwcQO5kqvXbhC5kH4Qtb+xzKrQTblKxtFA1OOvSBKBAPARE=,iv:6mHM+IxzV8+y3xXuup5qtE2o3oXrYCjAWvIQ6kjC4m4=,tag:Gqzzx6v+GORNaHE0qHLbmg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
