apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
# CLOUDFLARE_EMAIL: The email used to log into https://dash.cloudflare.com
# CLOUDFLARE_APIKEY: Top right corner, "My profile" > "Global API Key"
# CLOUDFLARE_ZONEID: Can be found in the "Overview" tab of your domain
# CLOUDFLARE_RECORD_NAME: The name of your A record
stringData:
    cf_user: ENC[AES256_GCM,data:8ISNnOESwy7t5fl7ve4ifdKl,iv:t7NkbVzprcbzICrjCqGosmX7+J4bkrHzkZlxNrN2kc8=,tag:9TKmCIyJSzWzyNPX1eGzlA==,type:str]
    cf_apikey: ENC[AES256_GCM,data:FmZIJPTnEBj6k0V+KvFZT1wLv561YQcA19xd3Pez+GtxrsrPbw==,iv:JUzo650XTFFcFvBweP6cgZfqKqDtmx/6iIJtkEfjn3g=,tag:dXPi3mwJ1OwilR3cjS6HFg==,type:str]
    cf_zone: ENC[AES256_GCM,data:8oVsYPNpk4bQAOLTHqnGJV8WJz1v57n2DbJ8qshrYTQ=,iv:NR5Qtd17dK+o2Q8xrHVrxO/PDv8AwkQHYzZfUNurvUY=,tag:hF5u0QVgQx/MFxg6I804zQ==,type:str]
    cf_record_type: ENC[AES256_GCM,data:4Q==,iv:wksXiXMe9dm5r8S2QxptxHgYO68CMxyruzSshir2x3Q=,tag:wIHUSBPv1ZI4rNAsqBdVeQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pqmv9umk70z2xyv8vvlma070d9rzr02j3ye8gjyv64ddf0sfwccspwsj8d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6QW5aamV2RDZOZmFNRlk1
            d09uUU9FRlVWMzl5akduRkJwdGlQNkZ1eERnCkl2STZwOFF0R1NheFJpR0IwRlpE
            RWxXTXpaYUR4ZzN0ek55bTMxY3hYcUUKLS0tIHgySDYzTEpUQ3lCYlVHaXFkYVNM
            USsrK2kzVktOZU9ZM2lITVpReGkwQ1kKAFeFR07vdYUtz4nehg70iSLwrmzNX7Bg
            aUT66nqtiXpLhP7CUoWM8FJBTCRbDD/pYPJapDUdxoInzhNWwv6xDA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-13T13:01:23Z"
    mac: ENC[AES256_GCM,data:sEBH69heF9pUKOtZ8IFr+hIQS9A0iAT/UdV3Xm0UY053aMFlniPTal99XtE/emfBMFJDSQ7aMErhp/IFVNMVEnjbklm7p1fwgruHwumrkQGTRYdDUKksxUi6oKUtQ4C2q854/d/WesGhFaIQ3rEr5DWAPKMe8MoKZgbrDbN5Yu0=,iv:c9St403SERo+KmNqTus+MwObJzXQmFJ1mMetUKFFmtE=,tag:nG2rw2pTJMbl3Cu7UzNGIQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
