---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sonarr
  namespace: downloads
spec:
  interval: 5m
  chart:
    spec:
      chart: sonarr
      version: 15.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/k8s-at-home/sonarr
      tag: v3.0.6.1342
    env:
      TZ: "America/New_York"
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          nginx.ingress.kubernetes.io/auth-url: |
            https://sonarr.${SECRET_DOMAIN}/akprox/auth/nginx
          nginx.ingress.kubernetes.io/auth-signin: |
            https://sonarr.${SECRET_DOMAIN}/akprox/start?rd=$escaped_request_uri
          nginx.ingress.kubernetes.io/auth-response-headers: |
            Set-Cookie,X-authentik-username,X-authentik-groups,X-authentik-email,X-authentik-name,X-authentik-uid
          nginx.ingress.kubernetes.io/auth-snippet: |
            proxy_set_header X-Forwarded-Host $http_host;
          cert-manager.io/cluster-issuer: letsencrypt-prod
          kubernetes.io/tls-acme: "true"
          external-dns/is-public: "true"
        hosts:
          - host: "sonarr.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "sonarr.${SECRET_DOMAIN}"
          - secretName: sonarr-tls
    podSecurityContext:
      fsGroup: 0
      supplementalGroups:
        - 100
    persistence:
      config:
        enabled: true
        existingClaim: sonarr-config
      media:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "${NAS1_ADDR}"
            path: /volume1/Media
        mountPath: /media
      media2:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "${NAS2_ADDR}"
            path: /volume1/Media2
        mountPath: /media2
      downloads:
        enabled: true
        existingClaim: sabnzbd-downloads-v1
        mountPath: /downloads
    resources:
      requests:
        memory: 250Mi
        cpu: 500m