---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sonarr
  namespace: downloads
spec:
  interval: 5m
  chart:
    spec:
      chart: sonarr
      version: 15.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: lscr.io/linuxserver/sonarr
      tag: latest
    env:
      TZ: "America/New_York"
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        hosts:
          - host: "sonarr.${INTERNAL_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "sonarr.${INTERNAL_DOMAIN}"
    podSecurityContext:
      supplementalGroups:
        - 100
    persistence:
      config:
        enabled: true
        existingClaim: sonarr-config
      downloads:
        enabled: true
        existingClaim: sabnzbd-downloads
      media:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "${NAS1_ADDR}"
            path: /volume1/Media
        mountPath: /media
      media2:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "{NAS2_ADDR}"
            path: /volume1/Media2
        mountPath: /media2
    resources:
      requests:
        memory: 250Mi
        cpu: 500m
      limits:
        memory: 1500Mi