apiVersion: v1
kind: Secret
metadata:
    name: external-dns
    namespace: external-dns
stringData:
    key: ENC[AES256_GCM,data:+MUDYdstHDGW1P2DUVgAqZLL2tng33N32AUS6NJQ1k94mhVlag==,iv:nArJEfng4X9U8DDNkmDX0eLIpbUpVoWXNJes0Cl/ao0=,tag:pagOG91Rpj1sO4Fw0fiqLA==,type:str]
    email: ENC[AES256_GCM,data:XLQ5oSJ97hPi528qJRxQMiRU,iv:hwHVCkuR0f7qZq5y4vXnHQ5143VKxs7NyQvYb3CtlVM=,tag:dJqOe1ltonxuKlKXR6ryNQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kmn982kderhq3468sre0cq9y93qmw4m4wk9eh5288a0reaa4xsrqpf0s9x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjd2NyUHFsZjFLaC9XZFI5
            TUFsTDFwVFg2aVFMQno2MXBtUHo4b0k5UmdZCmdvSW5BVEVtdCtublY2UGl3M2d2
            SVhBYWhTS05KblYyNTkwZkhub0IzUVkKLS0tIG9Kay9yVks4U2dUcTdDNk02d2hJ
            YmN0VXBKb1UydVBXR0VTY2E1Zkg4MGcKHxNP47vGOlPFOUl0wwFtssTyXecd+yt3
            eCUawJaGS5+8oR7VkqnS5RwY9sqhP6PlG738w6UqPpoGLLvymM+f4A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-18T21:38:56Z"
    mac: ENC[AES256_GCM,data:dLUMKzjRwiRnoATrhevG7C4evag4o71ST4SaqqGKA04jUi0p4J8doqLfXedXz+qZpsZGn30JDYeTdUEYc6BGI9rgToXEAHcfJd4Z0yUJ7Ek80ehYYROchB+NeYyXv3/lFHJdbnUoAubf3MGKWYAa2Ir+Xb07k2q6UuYPUDsbbb8=,iv:wYQPqQxnYXv/W/Gpoid8RK9fq3ylAj8Q0cSmQSEtu9Y=,tag:iHrLs+JOdJyYjTVcNoE8hw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
