apiVersion: v1
kind: Secret
metadata:
    name: vpn-gateway-vpnconfig
    namespace: vpn-gateway
stringData:
    vpnConfigfile: ENC[AES256_GCM,data:T3hy/FtIGwFuLhGF/5aC6cM4exv6VmIrwsdEClRhip3ZB/CpaVl4HKa+E1QzQ1Q7DJ9h17EDRVwUJu6swQv+uCsreDV8r/8bjMIZR8lyu6jZNxViDhJqZ49/8IBlqbpUq4pkjJILFX+CswNSXoXbI7lT1UvDodptXLWNpMC4cDp9+mAmgkJbxSfOEAx10hApIgAb7CPTfu9O6OclrGQbEBUA/E+j5BdkAb/ZRt4S24PoHF4mWjxDc0XJW5LMEtFRggvuyuazUxxLw6n0HPXzHS4yDdmEdYwCu7QbvSbMTloJjzlDcC9JJmDwv2D7atoDPdwnDjznzL70HfnjF1jNsa0SOBx9hddMDWR4v2h9xFjoiQ==,iv:8V6HQSnO1uS1VXBUnXD/iimhuGrzKNEcZGgSmr6nIdk=,tag:Vb82S4yZFv84g9IVrA22aQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pqmv9umk70z2xyv8vvlma070d9rzr02j3ye8gjyv64ddf0sfwccspwsj8d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2a2lZZHRvVEl4NnlWSUI5
            eGg5bm14OVdyOWxqMER6cHY3cGZJaXNIV2tnClRpMWJHNENuK21XUlRob2o2SHhZ
            YlpuMnRyUGgzRlpHR0VFN1dIa1hlT3MKLS0tIHEzWnVMYzduYzZOaEF3bHZXRHNu
            Z2EvYmlDTmNwTHkzN2hDY0pTTUFYM1UK6mD8bMKU9i7oq0lpgpUSjW7GhkT+iqzV
            VGOL9JKRtI9DaVYQA6H0C/T8PYjoOH9DJ35ZsgKOZtzSnfYJ1l0maA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-03-23T21:06:25Z"
    mac: ENC[AES256_GCM,data:uHYG4kqxxvShcUObHL0Y9+pnOUm0eK8CZlZyFF8Mcw58MG+V8z6DrLu6rbaK6gwWO+xsA5doEbgXWIf4dQjsKlXh7FbyJwxFBjonQWX89BziJx3pGt+CkwVdGsjEHgUsMDPxWkfnfjUPg/cu10x2cfT2/A8KNHHqsYrzq7jj6y0=,iv:fAmUqB5IxHiySohVjj0Wlnc6NfDOlmL9Ol+PMXWmrtY=,tag:y5oH35wSfx7T7BKayDVFEg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
