---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: overseerr
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: overseerr
      version: 5.1.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/sct/overseerr
      tag: 1.27.0
    env:
      TZ: "America/New_York"
      LOG_LEVEL: "info"
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          external-dns.alpha.kubernetes.io/target: "${SECRET_DOMAIN}"
          external-dns/is-public: "true"
          cert-manager.io/cluster-issuer: letsencrypt-prod
        hosts:
          - host: "overseerr.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "overseerr.${SECRET_DOMAIN}"
    persistence:
      config:
        enabled: true
        existingClaim: overseerr-config
        mountPath: /app/config
    resources:
      requests:
        memory: 250Mi
        cpu: 500m