kind: Secret
ansible_user: ENC[AES256_GCM,data:WZVCgw==,iv:QSQqZ++6RT1OcTEKAG/Tg2PKq1ewbLcBJqMsVpOTjxY=,tag:zINman5Qm3425hQt0g/WeQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:l1ubZAydXocM,iv:lul2CFF+seyu0r6wcViy2Iussml4Ck/zei/1KwJAgrw=,tag:6NJwKx/SnwJ47P7QM3cR7Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pqmv9umk70z2xyv8vvlma070d9rzr02j3ye8gjyv64ddf0sfwccspwsj8d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjZDRQa0hlRVExa3hjNDBz
            OVd0eUYzNjd6RmdmZmZHVkJCUWFndmI5b0M0Clo4ck9rSlMvY1hCVVdibnZITWlS
            L0ozZ1Jiem1EaE1yd0V6YlhzQ0FWeU0KLS0tIEs4eE8vMllUb2Y0cEc5V0VwRjBo
            L2dWMnJmNStvQldyandlM0l1dnVKTXcKgLOVcbVU2penNkmqq3Xw7ooYsSi4Kuvq
            ecPBUBl7n5XF01mVItmP1b8bmAZR3jwJ/Ou/7hGougBNW9C7n41xYw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-16T02:31:47Z"
    mac: ENC[AES256_GCM,data:qNrukWSVFjL5/3mxceKp29IVz3NUhItc0urk7naezng0yCyzPYp4u6hgYPHKmrWYgNGFG75Za2iWCKzhg1WYUxFR5j0M0rP/HPYndwx8ukLG+CjsRVyMXuVfTSgBEslMzPcdfvstiBd3oYzZSZanfA0riePGMZVpXrSILbdFzYg=,iv:sblKZAzc7PkZajrY+2fPHo8Lu+weGX5BAWpiGpIsN4U=,tag:ZojoXxMEFTRcW0LqC/ncIQ==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.2
