kind: Secret
ansible_user: ENC[AES256_GCM,data:RL0T0w==,iv:mq6AnTYDSkbZ3WQyNHnBfshnZB+4dl3GN3zF60aDDdY=,tag:Hiv8mE09UYEClH8GR4xBNw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:8ku7zF/AKJq9,iv:wln/9T9NtAGl07oTp3rBhPdyF78IxDxa3SfZUUX6ucI=,tag:P3KQEV75/uWy4He63GqzjA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pqmv9umk70z2xyv8vvlma070d9rzr02j3ye8gjyv64ddf0sfwccspwsj8d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1ZzBaWGNuNE9UaWFwdCtZ
            RlJLRXFJb0tiODFhNzZ6Vk5wbWZpZ3QyamgwCk81STNRTWNrTVpIbHdzYk1XVERE
            dDJ6MUhFU2srNnVPNjB5Y2wrRDNkTUEKLS0tIHJEZEJ5cGRSVXFwSC94V2dXUW1F
            SUU0MVNOeHRXS1MwSVFHVkgwaWE2d1EKBe/LF2QTI70LRHBWsNPgvWwF7zBRNbDo
            kBndWRHwOOfR2KNPq+Gk6yvvmAEpJ94lE0ZwXQJgZe2IA7eJr+QmGw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-16T02:31:47Z"
    mac: ENC[AES256_GCM,data:OYV4zgqzAMq5dOhLTUsCGQj+F7ih9JetrclbB4GeLBjzSDTzGc98pdHS8Wcelv6wt6sMK/2buZb9PDGGeRjIDHJLV19pSBCYps7taiTs5sa6OSLY1qIXkuwySMXCQNC9I5Xb3jT5Db7RVs+XTPajo9pY3iGHx29Bc7Gt+GMbEpk=,iv:+xRHbPvWeZpvlqXvYu2OJfO0Xqu/XnkfznNbf+VamWc=,tag:vk+waoL5iecorEvjVHbKSw==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.2
