kind: Secret
ansible_user: ENC[AES256_GCM,data:EbUF/A==,iv:3/VhCS0z/hr+FKCOFxQijL5+8a+3OJ5s2m5UJlp1+kU=,tag:GYwMUZM0IcE+AYANgXgUYw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:bBtyPHQeT1QS,iv:GrfYJdgK0dy+UbzgB3xR+Ceczl7aNqXkP/k4sQg0vh4=,tag:9OwCzwqg56P/V2xvfK/jtA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pqmv9umk70z2xyv8vvlma070d9rzr02j3ye8gjyv64ddf0sfwccspwsj8d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKY2tTcXV6OWFhb3R5NUUz
            WStBOWM4R2VPU04xR0lnK2dsSStJbmtiamtvCmpPZS95SW5DMHlsemhUOUhVa0hj
            bG44TVFpR3FwYlp4d051ZzZvTXBybTQKLS0tIE01SHhyOUF0MU5MUFg3RWtrOWxQ
            emlwMFNzVTIyZVlQdVBVZFdGeEpPek0KNZ3KlLTOs66LdzW30Pii6fSCvLlxWXzO
            p4CxpAcmyGzHwlzJlP3SAU5PFA3k6Rv49r7PMA95NH+zv1Cewo0ajw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-02-01T12:12:54Z"
    mac: ENC[AES256_GCM,data:N6K8zLo52eYd8sKeRtnDqifgmhQP9zNEz3bjqFje7148etcVQxHzXdhm4paZQjkR6zHmMXyR6yfp8nMoPCK/IpNZC3OhMXT119B3ZavjFOwvM7/OPwrY8pK0Oo4Pky2GS9e5DtI22LvJd57aNE7Yao12fio1azWZvJuW22Y0gk0=,iv:iQUmBiHW0hppNZHHix+WS4JhdS0Wgbu1w27wsvfyYIA=,tag:PnqOsvQZ16vXgA3qDoQ1iQ==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.1
