kind: Secret
ansible_user: ENC[AES256_GCM,data:GTVBRw==,iv:hhGBnKJHxCjhHb5s3tGdxIphqyXSrWkoobFDTBI7m58=,tag:RrkQkvgr8dvzrIKSC35+lg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:exJRG8Nqzxpo,iv:JtvDPjbk9Yx5Oy55ye06kkiTyR/AJov0VTgsPbELksM=,tag:2GiCiq+yT5Q+GxtnOHt11w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pqmv9umk70z2xyv8vvlma070d9rzr02j3ye8gjyv64ddf0sfwccspwsj8d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBscllITHd6RFRpZXUrMUlD
            enhBMjB0anB2eXJPK3VVYzdTQVd3U29tckVZCnhmUG1tUHN5TEZZOVBoTUE3dnlp
            b1hOL3pRTXUzTWFWT0JyNkZRbjR4NjgKLS0tIFNkektrWW92MVh2ZzFkSEUzUDJC
            QWtWVm5jZUJIOGlNSnFEWXRQZXVMZUkKVLX+sDYZoHHSEWw6Pb7wqgn9pD0MRxza
            SFWYvnZ/8mIG+Y/nAFDCbvHIw7jG6R0kRVN25IMYIcNOYxMbJ5xAaA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-02-01T12:12:54Z"
    mac: ENC[AES256_GCM,data:vvU4Va1/ZOxPVNkrE3LVMJlMWAQeSLbwdpDZNjegIy1NZu9mLlB919a3RIHgVizLxk7mZ9XjslpHI34dQBCt5Kcg9g2+J2ZnCMURWfMcxlnEmj1TWyF58TVKLp6B14549eQs+yuP1ejCGEpkLa1lHs7AldIRUglV2YFKxiQBhk0=,iv:bh8F9km4pNs48rXQQJzy0F5/aH9rsZypseotftzkFO0=,tag:qdOdZXa1BSAy2fWyJoWLSA==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.1
