kind: Secret
ansible_user: ENC[AES256_GCM,data:igkhyA==,iv:8dh1tgSc1+xw62tunGKwBdh61Ho2RtqN8+npswjyJ2A=,tag:IvgQI2A5QkxizcKyYRmV7g==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:XMnHgjg3e/Bp,iv:8iR3JSOaVphsDtxWAeGdVLe+cqWF3ZVn0hkC+58OSHw=,tag:PynvG5aQB9TCwkj97pScNA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pqmv9umk70z2xyv8vvlma070d9rzr02j3ye8gjyv64ddf0sfwccspwsj8d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEWnc3b21aelQ3SUE5cFFr
            R0E0eTJmbnQvTC9yRVZTaU02bEREUC9ieVZFCndjY3hhZGVuQU1uZnZMUnBrbE5H
            L2ZIUXcyT21oZzl1Skt5ZkE5N01BbVkKLS0tIFpQWnF3eUFOYWIwRHpaMHVoNnNv
            ZWdEWGdVZ2NnZ2o2Q2prTkM4YUVrYjQKj3wvCnohuVx/+Jgyhxfnf3G3erI6lqMq
            l0Hxb/Ujr3HKD00E9J3mThjWetfWGM8APx0EsaBjJIoCp4DiB6VSvw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-31T22:34:31Z"
    mac: ENC[AES256_GCM,data:TdJ6rn6CFdMGBz37d/2EmU5PN5sd6lSGcq0A170aG3O5j/LA+IoI2zL4oikzBjF8RTK/Yi+YnPLQotRCpnu75aB56zqkBk2UhnG2IcrpbaVLoyGcrWvkgi+BqOHr4JWmJyFow7b56KaD3q3W/suPPyYpJO8jycPMioK5k5jEexU=,iv:O+eN9RWBgJqxIfyWj2u2kk/rwsOfkzXiBZ2n47WcFDI=,tag:mkSUEi6LO9fb1kO/qDQqCw==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.1
