---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: radarr
  namespace: downloads
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: radarr
      version: 16.0.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m

  values:

    image:
      repository: ghcr.io/k8s-at-home/radarr
      tag: v4.0.5.5981

    env:
      TZ: "America/New_York"

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        hosts:
          - host: "radarr.${INTERNAL_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "radarr.${INTERNAL_DOMAIN}"
          - secretName: radarr-tls


    persistence:
      config:
        enabled: true
        existingClaim: radarr-config
      media:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "${NAS1_ADDR}"
            path: /volume1/Media
        mountPath: /media
#      backups:
#        enabled: true
#        type: custom
#        volumeSpec:
#          nfs:
#            server: "${NAS2_ADDR}"
#            path: /volume1/Kubernetes/radarr
#        mountPath: /config/Backups
      temp:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "${NAS1_ADDR}"
            path: /volume1/temp
        mountPath: /temp_dir

    resources:
      requests:
        memory: 250Mi
        cpu: 500m

    metrics:
      enabled: true
      serviceMonitor:
        interval: 3m
        scrapeTimeout: 1m
      prometheusRule:
        enabled: true
      exporter:
        image:
          repository: ghcr.io/onedr0p/exportarr
          tag: v1.0.0
        env:
          port: 9794
          additionalMetrics: true
          unknownQueueItems: true
