apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EMAIL: ENC[AES256_GCM,data:lU/ckeCyWmBYh4oHDHnZ8xb/,iv:6KnNx5Us26O2toH0hSrypcMeJKvb3Fz7hygBmiMCwDg=,tag:n4QFn2WF6B351wgeI84hjg==,type:str]
    IPINFO_TOKEN: ENC[AES256_GCM,data:kyfbXCj/3sTI6O822YY=,iv:3eGDW1EUKg1/+wdNnfgj943H4lSibWoIoBaj+5lY2BI=,tag:jcMQ0nYiSg19x1cQ2m3+yg==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:RrsMGp4od6p153V7Lwo=,iv:cDqNwPhQZe1hMOqw1qHxbTi+Y3GD4tO7rulFPNTxE2w=,tag:PvlaXB9Zmwv5wOb55MJnIQ==,type:str]
    INTERNAL_DOMAIN: ENC[AES256_GCM,data:ax2/GnOhpAydnz6mc3AR8rtCIA==,iv:0UF6LIr12DV2pHxu6FID7IKSfY7wfcFvkS7RlsEjNt0=,tag:FnCAWsUOYjqK4/G0Y3Pe7g==,type:str]
    VALHEIM_SERVER: ENC[AES256_GCM,data:VS9iPzTmDvpbbZtP,iv:+0ZLHaD2LelrgqnpxqUNiE2aqO2sbT/t2h1012m2jn8=,tag:GkRBtOXf2hdPD6w/qu6jsg==,type:str]
    VALHEIM_WORLD: ENC[AES256_GCM,data:sVBve0MfcvpHMw5l,iv:j5B8vsLS+ELHIqQRzu/Y7054Ku5lRgg/ptsZinrgYNU=,tag:myvF1cuim9gKgrsY7dhSAA==,type:str]
    VALHEIM_PASS: ENC[AES256_GCM,data:2p5urefnAcY=,iv:74/mH2xqZ8XFusyTgq5PfBX468zFmbrqfQq5Cvgmi44=,tag:fztASqFk4xb3IdFJLkQXug==,type:str]
    SUPERVISOR_PASS: ENC[AES256_GCM,data:aPGJxSgW3tAV,iv:w74a+pYdmbgqIv3h7dD5w3asKJrK017c/KU6Bl9XG1w=,tag:WbM7fDC0S6KgWIRVe6NQlQ==,type:str]
    LOKI_MINIO_ACCESS_KEY: ENC[AES256_GCM,data:b/JrZfWSadFXUAmyWw==,iv:BB1rx3jlNplxKuLwM3d4cVpwxUcQ9Y8TXwfF8zndN9o=,tag:kynBZu4s1fVN+9dlXm8OUw==,type:str]
    LOKI_MINIO_SECRET_KEY: ENC[AES256_GCM,data:sfXN0XRfoXavVhBEGhmoUwR7fa4Z4BNq,iv:4FW4psbZCaNpmpr0EWEJoCM6/+4AFNd3DwO5Qyosbrc=,tag:CVdEKQjIZrI8owPUXQKC9A==,type:str]
    SECRET_PASSWORD: ENC[AES256_GCM,data:Mws1IcCfSHJV,iv:Ljowaot2Vbid+2QalP3bkCtBGVgnrSpkrbWqpXJlaLg=,tag:NEyENwRoKbgrpocMqRFynQ==,type:str]
    SECRET_POSTGRESQL_KUBE_POSTGRES_PASSWORD: ENC[AES256_GCM,data:CKx3CilmGNCx,iv:hdURZfecgg1cRvk8BZ86Rs9564tOimiNajabCWx2Ny0=,tag:IuGWhGuq45ZxhzvQDgyDxw==,type:str]
    SECRET_REDIS_PASSWORD: ENC[AES256_GCM,data:7JTS4wuAFtka,iv:vYLs8BDY04w/1ITXqpe/XfvJFBPCasMKXV19aYuNpm8=,tag:AF8skCUyEVU/xpsh6a2X1w==,type:str]
    VALHEIM_DISCORD: ENC[AES256_GCM,data:/4UYTXb+GCTyzsIzDqBRQz88NbMUVhyAXm9MCiTbq3wn/zmgdeWn7dAso3gLDoiBtcBmBru/1vWUi7toT4cAI28zmg7PlhxgGAZW1/XywTglxfwV4g8V/BfKADjMPNoNVZVd/X2RovxpRSnn8YjZVyByWGz1aUYT,iv:A0dnxjBhH2R1/m3KkvhzZmbe68SHc2G4vNTWozrRnrM=,tag:MU83C+gu3h8efYEEHsBTWg==,type:str]
    VELERO_ACCESS_KEY: ENC[AES256_GCM,data:FZzKI40W,iv:lD7SLv5KGilgBqCUyidR/OTnvuib5r9A3ZasqK8ueMk=,tag:aP7jNEMnV4Aan4u0b3t/7Q==,type:str]
    VELERO_SECRET: ENC[AES256_GCM,data:rufNMZr+Nh63P/iHmdlYOVnoQ0XPRVcjKB0=,iv:KdetPMHjPMrjd+tB5BYmUyRdfxJBewXMUuhZGJfEL0A=,tag:X+RpLWvIEd++pgmi+SiJ4A==,type:str]
    AUTHELIA_SECRET_PASS: ENC[AES256_GCM,data:BkftKdoHbf8Vy/skQLbZCwnNHiVFjgO1D05VBJuaE5wAxNKJ9pgQRQYgyGcGBJrc5YZp6zt791dssM5Ud57zw0IjFg6iHEp8ah903j4mJZC1ROGypw5ni5u5dxRvaPdUQw==,iv:+7l58gl62N8e4cvGyDNjCv4cCTk3XP3mdapgrDH5fUU=,tag:SPSDqvuPXY/T2ORmVuN8Bw==,type:str]
    SAM_AUTHELIA_PASS: ENC[AES256_GCM,data:3QBTlOzQPd0jd2vjtqevwY8fOmWaiuJChpPf9YES4uZ2LHDtjFCJZxzBLQ1n8qku1nh1Aa7S3YJc7hPsI9C7t0iWwpqsGddfjkGk6KI5eTHqx/BWRxnc8EQ9/6zIXhApTw==,iv:9LPygNDzC9GZLzHsfwh515WuaDtbGmo4v+bsC65U6zQ=,tag:wkffgF0qupZvNc0R8BM16Q==,type:str]
    SAM_EMAIL: ENC[AES256_GCM,data:NcqvfecvVROinLSRfm/XIZbJVQ==,iv:VDdlHL64lRzDRoyPRh6/tcaZ6TZ+/9JY2dAogUEik18=,tag:20ECSkyeAqdZjv6Ug/TELg==,type:str]
    SECRET_AUTHELIA_SMTP_PASSWORD: ENC[AES256_GCM,data:Nbtb2SSXVAVh5lcaFUkytQ==,iv:dzL9oLDvh5l9CwJpCcW3dz/GsG62a+/vKlK9RdPXzDw=,tag:vVE3nrmHkEsmwRFjwWvArw==,type:str]
    AUTHENTIK_KEY: ENC[AES256_GCM,data:ja8Of+YaDYT+ZpawNvEWLAjmxwAUggKANi28KVXv9X97ptM3OFWiPkXk+T9kBA0jDzo=,iv:E72UiiVU442Pmo5ZshtevvZjeZ+7qj4UWQadgsIqmiA=,tag:f/svtTSF75aiSMiJGjEK0g==,type:str]
    ROCKET_DB_ROOT: ENC[AES256_GCM,data:d8afK61bEO8usQ==,iv:7lOG7j1pIE8GsrWDJokDDNM6QKdGf31w6xuD7ok/Fto=,tag:m6IqJkw8NnPmoqQ6CPKMqA==,type:str]
    ROCKET_DB_USR: ENC[AES256_GCM,data:txfZY29+myPMOQ==,iv:Ueq2XyS/Yw3rsJBZjyCWKZAdkLAajfmVSb09Vm4/yWs=,tag:XTj8jp2kybYr2UbJpYO94g==,type:str]
    ROCKET_DB_PASS: ENC[AES256_GCM,data:5dTckAyckXEORg==,iv:8WGm3ghdqhzMB8Z6J7+ycmBeXJkyrppiPy12gKpSLG0=,tag:+hupw9G5wxPs/P5Xscov9Q==,type:str]
    SECRET_AUTHENTIK_POSTGRES_PASSWORD: ENC[AES256_GCM,data:EjRc9+GD9qjcWF4cDCB4+a3iAhII,iv:foBzCwSR0rv/1bh7kBRK4knqGK0GK2+8nBk4FrGwbhY=,tag:iIps6d/17g4/IbHwMrSQWg==,type:str]
    SECRET_AUTHENTIK_REDIS_PASSWORD: ENC[AES256_GCM,data:j4T3bFcCajx9pRuw15Opyjjy,iv:qqW0Sy5qlnOXIOmPKUOV4vo3ZgSK2WvzeiL/ukEf1+U=,tag:w6h/I80E8bQzk93eAtxUlA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pqmv9umk70z2xyv8vvlma070d9rzr02j3ye8gjyv64ddf0sfwccspwsj8d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArVUJDYVJYeTlBa3NuUmdq
            SHc5ZXhtbmkySURLcUVMbDk5WEJldTJ0dDJvCmd3RWxpZXAvaDM5eXdXT1dKT3Zn
            b3NFT1ZnYktLVHZESEZHcTgwVTZvTFUKLS0tIGo3eTdBYlhQeXlRc21SRWtGeGxF
            TWlSV3pZU3ZnNElMUkJsYkJxWEtGakkK18wLkYByYX1C7a9lKyJ9XOMwu82TBxgF
            /ndLYXMuM9VksICLM7olFkucWwbHZuQByud+FBZ++qdINyQv4AuCVQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-02-23T18:39:55Z"
    mac: ENC[AES256_GCM,data:hgxVw1oycGhZC7UtfnX1EfKcPZPo5J3FFI1rHKaYb3Ot58REJL4h8uafTfvc5T5Dv42FtYrglBWO5VtGlHoocvtxE5uj6xqiEG4BXieyjaw6SNfrdfVkwSp4SRFFI76RAfOX/ld1na1XS0UDHMmh+5ReE57phJiYYcwYeKRiexo=,iv:LIvLvYVwVlE4GpRy73ubCXhckyjYNxsdnu4EaJcNrS4=,tag:+9QzlpiwV7K5Lgvw3Bf9ag==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
