apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
data:
    SECRET_EMAIL: ENC[AES256_GCM,data:CDGU6fr3Q5MFpfFopIlLKmzaFoLehWVC,iv:kDP1uiqI4Rd+oWtmadRqsBS3Agr34jIMWlxEPZuIqLY=,tag:WYCtlMeOT1iuwn49p+YXNQ==,type:str]
    IPINFO_TOKEN: ENC[AES256_GCM,data:AOnz0Azy2A2Uf99kSGo1gFTOAFM=,iv:vn2MBdllXaO6tOe9S7MR503+u2jnZG/Jsd9mHDY0omU=,tag:G8NejrGAn1Q1Bi5xqhp1gw==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:k5/qHoPudszX9/rnilDchHt/TATpStESQnwcqQ==,iv:ZgQPyGGq3beIRJYOmf5wcxv55Z4scxpWd8DzOQ/6+Hg=,tag:CEyw1rrWxO4xJFZeMw+Vow==,type:str]
    INTERNAL_DOMAIN: ENC[AES256_GCM,data:omrXn11RjTx5q6h4PfaNIe2MvJ2uYd+xKKOI2A==,iv:zkf/D/ySMuiXg2yRVvJ/T8H+SdhGKM2X0ZqeBQpvXrs=,tag:sCG7Hgkd5DirBJCIHrhseQ==,type:str]
    VALHEIM_SERVER: ENC[AES256_GCM,data:1LIxB4N2pMHOsD6+76yQ6Q==,iv:WZFNFknd2SMPLgFdVePprWbiiU6LgH7K0d93XfsRFdI=,tag:R+w0loQdE6Cxiiq4S3HNSQ==,type:str]
    VALHEIM_WORLD: ENC[AES256_GCM,data:BNj3egfiYXeb6bBBW0pPdA==,iv:x/JcEaVecMMGkbE1UOQjmEnv+pkNxbHmivlhxbKiot8=,tag:QgXYoSs/zqzZLyUQ+9NVmg==,type:str]
    VALHEIM_PASS: ENC[AES256_GCM,data:L5NuW7xUY6jUk8ql,iv:Q0rTP+ELjrTMTghEgO72x7fpvPThtuh47qS4MvXc6CI=,tag:+LfcohPuDg4ckx58L/Q4dw==,type:str]
    SUPERVISOR_PASS: ENC[AES256_GCM,data:NNr3i5TBJ25h6RT8,iv:AX9Pltj98YOl47fhsH7xwfkOkoBNl8JwZHR1MLF0yE4=,tag:o17ZrnSz0obebTc8GppeUA==,type:str]
    LOKI_MINIO_ACCESS_KEY: ENC[AES256_GCM,data:TpDPRS8LO0X0zstu+g8v98drEmo=,iv:tPd0Vo8UcpWggxPzFOcSVHvd32h7YeqI8BjO0v9tEDk=,tag:fUhhqAWe0eNAS4BICG+kiQ==,type:str]
    LOKI_MINIO_SECRET_KEY: ENC[AES256_GCM,data:NjZCbU46uE5SzkXO1zcmCpGw7NmUAY0V85I6KnNgDRI=,iv:mlnNXOuO26jUNhpZ2tzwV/GZCTBxDIvuuPsJK4Ha5IQ=,tag:sQp9U26Yrt+dmZHWjwovDA==,type:str]
    SECRET_PASSWORD: ENC[AES256_GCM,data:XSQhAKXsWhB9C7uH,iv:cpkak5vju5iHzxX3OqNHB7PdlDuyCAPpNzv+e6JsmdA=,tag:tWLkwscLe/SunSrAm5UHxQ==,type:str]
    SECRET_POSTGRESQL_KUBE_POSTGRES_PASSWORD: ENC[AES256_GCM,data:QHuvl+Qx9MNvmSoK,iv:2GyW4TDZHTJfvfaJ3K3wjnB2Ul6PBkzx4iLQRPyGAI0=,tag:6f7KTcuTLGcx9nfrID7BjA==,type:str]
    SECRET_REDIS_PASSWORD: ENC[AES256_GCM,data:G4G7kOHn8cBd7UMT,iv:BMvJ78kOT/hRm4kbJucFHbmkbm2Z8KZkr9ITcj3APTQ=,tag:X5m7urPR+R8A89QWox/nGw==,type:str]
    VALHEIM_DISCORD: ENC[AES256_GCM,data:uQ+iOdPrrlzmfBttWAcvdmwurEZOCIxUrA9drm4PNU2MkRkbIw6D7kBh2OK6vZEOWhDlX0t7fiNEVcmsswlH+GiQ9zFf8k8y2BahmzmPLe42Ng9MknR4NAAvfP3dyWNFyd4NTD6z2vOSLiPIpbAbae7A3fhRseNdkzueQCm77+rKziU70Azdl3KSmxFgvkGw2TJAsnddV0V8pxHFK2rWFw==,iv:jYmFu/WvfJkXrZysJyzP4wb/wdCFapTEjCMuTYG0kYU=,tag:HOhbZgCH1E2CoyvHhEYLyQ==,type:str]
    AUTHELIA_SECRET_PASS: ENC[AES256_GCM,data:3KQtvorEewMXcc2JwE7Y6r59m7/e6DxMcQ3OCwOKsyvzq/9gzaFfBQL08hOr1TwaJl0MeXQr6GD2ZyxAeKOSnGxxsjsOd2KGo11wx8lEveHKwOeHXKeyniEs3FWmjSnt277ZTdZsV/5TOjvT8x7exKPR+T7NJ9iQdiwuVaOjJz8gZw/R,iv:YBtuTWNJ/tIKp+hAVkqnJonX+7DaE0gQqukvmntWpAI=,tag:YtpLpaTOyWpSFsEcmJGYBQ==,type:str]
    SAM_AUTHELIA_PASS: ENC[AES256_GCM,data:TT0gN8r3blV1DbcD8p5xkkLyTykr24VVW7/sMSYSKCKrkvlZaFy/bPV6gRNuErPi0S4UfNLwrPiyawEUNfe5S8HVuGeLGPUfRdVN9QsZlfyOwpfaQ0BrW4DzdPfeGzwUEJ3mBmrDiHW6MAYaN49Sx/pGyPLmz5W0dC8VuZIGSdDlf6SI,iv:zRUwrUKQ8/5Vjb6/BsxMM4XGXuGpxqzua7pDWJtkea4=,tag:Q1oCIIOrMPpoTVVQkhIcUg==,type:str]
    SAM_EMAIL: ENC[AES256_GCM,data:3Mg0A9wTos8yfi8pBDEywwJkoPckNVp9XFfYRw==,iv:2Im3RPgSDPcWzh32uhTjbpQi8UwjvrvxM9wxAatrw0g=,tag:kTIMqk3tTEeUIi23xmuwRQ==,type:str]
    SECRET_AUTHELIA_SMTP_PASSWORD: ENC[AES256_GCM,data:t2PQjJFDQRRnWhIEfyUPIJ1oDEv3vWwP,iv:YN/P2bqEmrCrsITu8ytJGpa4DrSU2NrRcx0XqzGasBM=,tag:ZQMI4YFH6LFdJa5xdieT0Q==,type:str]
    AUTHENTIK_KEY: ENC[AES256_GCM,data:7h5i/Q27/ctTRr5cELZvzLeXtftU972vW0lQji58XtXo342cBqb2Eh0TRR7cg/B+csb4l7tReT172zJ3yDteJUoFD9Y=,iv:r3MGSnDgOqc0uiA45DcRSTNeIL1UZRnwvVIQM7v4kV8=,tag:jDU0Pubogb/CNn2qFI+bgg==,type:str]
    ROCKET_DB_ROOT: ENC[AES256_GCM,data:mRMd1lrXPnb+dw4GXz7Cgw==,iv:mszUxE5yWROJ7gwRym8rBX94d0KhMghOEVSPOHPmN44=,tag:Py3zDKpBPkPTSY6RjRK24Q==,type:str]
    ROCKET_DB_USR: ENC[AES256_GCM,data:zPhBfOUf5+6TEsJSrX/FMQ==,iv:i17deOLG/QkZZhrzbFeM0kiC5D9IBPJLJOFRLAzdUV8=,tag:GKX4nPSC+4u9TLELelG01Q==,type:str]
    ROCKET_DB_PASS: ENC[AES256_GCM,data:vB8u6rZ3dOQHE25quTzhRg==,iv:3QyaKuJMOim5biAVtpLj6f00HQShLumn8PZ8bbILHVs=,tag:nUz/K2DQi1R3fliHodPwhg==,type:str]
    SECRET_AUTHENTIK_POSTGRES_PASSWORD: ENC[AES256_GCM,data:LRqiBVwNm+stRBa7xfuUoieLWz+Nzl5lautEUw==,iv:eby4PmJBJVEjkkIbbb25NAL37ivD2KYP5PtmTDELqoc=,tag:490HL0XbZ9R9DewIG3odfA==,type:str]
    SECRET_AUTHENTIK_REDIS_PASSWORD: ENC[AES256_GCM,data:yU8LRhYdWpogP22dv0EgIssMZ4+qhUb+,iv:PJ9goedNJs5lxGFMUOIrSqLqkqn+8mh81bAZCsnOVhk=,tag:u3IFQbzpW4HufFsLWNJH7Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pqmv9umk70z2xyv8vvlma070d9rzr02j3ye8gjyv64ddf0sfwccspwsj8d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4c0dHME9oZmViWDFhR0RG
            bEFXbk9jbFEyK2w5bkNycTlVeDBvMlJMZTBZCmtITXRuSXVDWlJQUkdoVTJzaDRw
            eXE4SUNmZHNYR2pnR1hIaFAzSVFhSTQKLS0tIFRpaXpUYjJJNTN0Ylc5WmVLODhG
            cEc1dlhZYnpMeVBMSi9OU01JbFp5TTQK5LPXm8lAsk6NRyRVoProPLMRXLZch+M5
            LEGR2TlR6n0suPsSUI2A52PbJ6dkZZRcF1yQJI/V5ImpOWo52LEvqQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-02-23T16:58:31Z"
    mac: ENC[AES256_GCM,data:J/4nnS92GaWr/0UsMdt1XuAhup6py/c2N+RD0nvbsiF9BftxF4aZhJ7UiWQBb3lZnun3Aisoj84Zlcv7yLG715T0Q7bplkRgPqZsdFs27YRNDmv+vq3LbjK+ZKy3bjtyKh6mQrQrZ3YtE+urR65GfyErXZQjx3pZkELU8cKOX5o=,iv:DRAfwu++xiZFsYB1ZKJpfnhV5xbnBHlYh56g78b+5pY=,tag:qnc/bEDA0EMgBzUyhoGvkQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
