apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EMAIL: ENC[AES256_GCM,data:TbbbgdqpALg4OyPtgMJmCfqn,iv:h4ROfnrVx/s+O+uhUbx2vIuSkM8ZXj4//zu3qQvLqBA=,tag:wwwGfvoyS2Zrzp1Q+2FpSg==,type:str]
    IPINFO_TOKEN: ENC[AES256_GCM,data:VpXvas+GiR9I0/AOfGs=,iv:aIi5t6M4OpUVnzn3FH4t/qAjxVT0F5c31cQG/dLRcbQ=,tag:Krv8HpQBqr5OAbZ0jIbWRA==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:RnZ3FwMJJ+ngsyDgz+c=,iv:toIFe30FufxEB4+CbzCxG/EOTqznhUysZz4ZuqjNbBg=,tag:7Ae2+TgIB4maU/+68Cl2Bg==,type:str]
    SECRET_DOMAIN2: ENC[AES256_GCM,data:q/UnVkqUaNQL+6HK+A==,iv:biHruZkS5iNFBbokVdf1tXzpwf6zrpiXlD9NoYsqzfM=,tag:e2f4Fl/1SUbCniXKm+q/qA==,type:str]
    SECRET_DOMAIN3: ENC[AES256_GCM,data:twMxDLGvlk208D7fCTg=,iv:kY4TCxAJVNH7B8wE8PPBgLSKnVvvWZevYy8Rc6VIZqo=,tag:RbGQj763pjsIwT/SbDuNNA==,type:str]
    INTERNAL_DOMAIN: ENC[AES256_GCM,data:9pGCd3X9ZkrBaBvl+OfiYuA4fg==,iv:9HSdSkg/g3AFpkJjdk2fU1PAVnZvpxc3LQqRw8BjVZk=,tag:xPKNWjn+B6WYoKPnryH3Bw==,type:str]
    VALHEIM_SERVER: ENC[AES256_GCM,data:+dhuUhhlqLGOMyAa,iv:lQwUIBDDZNmVW3GN7MXw9N3bsxZnV1IH6FrXjVox0aY=,tag:+gvrLiT8hK65epI9m70qLw==,type:str]
    VALHEIM_WORLD: ENC[AES256_GCM,data:wYkV2U9Z+UpO9Tpl,iv:b3/5g1N5hBtlQ9hY3jjnNHU3YROGg5wH+bWGGW3z01g=,tag:bLwavY4Iy7E9FSzG5YKwEg==,type:str]
    VALHEIM_PASS: ENC[AES256_GCM,data:x+fecfmAGHM=,iv:LuZ6qYQDtT+3U6hqdPVsTrp9/CyJ2jD+i1Y658KljOY=,tag:IBsL/ws0Rf6hB3QORXWERQ==,type:str]
    SUPERVISOR_PASS: ENC[AES256_GCM,data:YMy2K07yZWbS,iv:jOqRuTMAUPn8atuhV/2USFFTFeKH9rLa6Y3RUBpFESM=,tag:ElSu76t3vRKnAGkoVoU3Bw==,type:str]
    LOKI_MINIO_ACCESS_KEY: ENC[AES256_GCM,data:hzWns/2vMb3DHq/7xQ==,iv:O01unP+IyS85DgdZ1oXPcsAnjY8Ceoh0Z0pyqVPLahI=,tag:qBIvn+9uJEvW5yOmcQF5xQ==,type:str]
    LOKI_MINIO_SECRET_KEY: ENC[AES256_GCM,data:M5XxpKNF++1bL2q6QgqEDuYM+oFErb6v,iv:s/Z2/k5N6RiBBAp1VDA0WY8zCXmzu6FvoNtZCW+Vpks=,tag:8cKD9JZIGfL7WGfZldfdIw==,type:str]
    SECRET_PASSWORD: ENC[AES256_GCM,data:/8HW19+jJQWY,iv:28z3nggHk+zOFqsRQNf6X4g5lHz43ehGAcH7bl4HPMU=,tag:ohg82uWNEWCcPBBOAUCbfw==,type:str]
    SECRET_POSTGRESQL_KUBE_POSTGRES_PASSWORD: ENC[AES256_GCM,data:6o25YzWDDd62,iv:FGBkJ/dR+NXedlXCs6+COhBzVW+fP0ighn4negDUOo8=,tag:HzPwkye5StIXOrsD1jcdNg==,type:str]
    SECRET_REDIS_PASSWORD: ENC[AES256_GCM,data:uHPGWI6xaCo6,iv:OCovYOLG5p13d6/6YgVP5PPiGZG5sjjD/sc3CtRklEw=,tag:w6qoqR52NVBGrNHd2tGByA==,type:str]
    VALHEIM_DISCORD: ENC[AES256_GCM,data:BRxBa6t3+t/j3mHGKL/96//7TxxAaf3FCZ5HrZsRnoDvOlBEvQwrcJgkl7nAsuk28Z4jJ/BjDSuDvWiWKCyWNEiWDnU9MTjasbNI1QUcomtqXuH70H7HjhjrmELDUHXyf3U+TYyVjbKSgrGTH6d42cuIdpPPJwj5,iv:rry55yk8FPy2UefClJZkNojKeud3Vy8wAbIHieTn5us=,tag:DcKgXYvmKVqKKzDYMKxioA==,type:str]
    VELERO_ACCESS_KEY: ENC[AES256_GCM,data:O8WCn+RA,iv:j4W7zm/CEv0/Dc+oREtN2ZZlxw+DXyg/ZiQiYGLhin4=,tag:aNT7nkikO9o2cAuZHw4FBQ==,type:str]
    VELERO_SECRET: ENC[AES256_GCM,data:yOedZq07YorhnStU9Z0+a2XVc+p4OtPP42s=,iv:s5E22LJJa4JdVGB/L+eqx6pL+nCfHo+daZtcGj9Fqr8=,tag:anyfX1x86YO8a2sen0GVQQ==,type:str]
    AUTHELIA_SECRET_PASS: ENC[AES256_GCM,data:XvlJzCG+SsGy9Ov8THatE8fEIj6bAdl83DWLI5pJcKxhEmsZNln9vAe+TS3yW7P7/GnjxM0R5nTop5IcSilo5h8Wm143iGSvC+hu6jhIUPS332oZXLirpWW1f8/uYU453w==,iv:BtoLT+CZb6M0JodXbnqc2+t2sHT5ISwHn8tjEHCedo4=,tag:lCFFc0zbT1RjW6Hz4G1XLw==,type:str]
    SAM_AUTHELIA_PASS: ENC[AES256_GCM,data:eDwtYTFYK0TrnZ0quh9Lfi/sNkMj4VLfpHcQHEc6DhhPfF1WhRQA2ogLIwm1Kj+eZSFiiA1ZtYbbk70yB8vGn1BZr1p+crawIaNDX79LrE2ZGlscROeDDb7njsT3il6HGQ==,iv:ph3rQmNtlV4y+tWIsL9CYhNT8gdrmakzWSAiVu5FzTA=,tag:o9vRmT5ZE500Akcl614g1A==,type:str]
    SAM_EMAIL: ENC[AES256_GCM,data:My8t2MGzbkMWmm0pFu3OsH1eGQ==,iv:Bt9XrvzJh7Pe2hOUZwMt+z7Returk1CBgKuCVTPtCpU=,tag:uPn2hkCRioF+h0dIHAD5gQ==,type:str]
    SECRET_AUTHELIA_SMTP_PASSWORD: ENC[AES256_GCM,data:lujdSExrtef+akzXyZZXJQ==,iv:97/iOccU4LjmrdlCVP+ELeNw1skAWJIn9xPuKbIEzh0=,tag:HpbKf82g2MePqxVBqk03gA==,type:str]
    AUTHENTIK_KEY: ENC[AES256_GCM,data:AEcWlYeuvniAfSq49rrqLTZ2ePDu90BN1ZZL5TThNTbgmWEQ/Ls3ia2RAMybWbwdlq4=,iv:AEc8259ZkGWIXkZTcRHB3HA4aoYBaLfG4dqxJJnh7tw=,tag:+0INbsBtj9i7IvjSU3407g==,type:str]
    ROCKET_DB_ROOT: ENC[AES256_GCM,data:92zzrLooRqNBCg==,iv:Y8iupHL28Nj4OAfH7zlbU8RQb1+adjrW4PFzVEqzsFk=,tag:Ki6XrkENIFLJ3dSW36RoHg==,type:str]
    ROCKET_DB_USR: ENC[AES256_GCM,data:NYpEW488uTj1Tw==,iv:yG1dfZK6VOB8nUMocKCa6nKMkA7M5DIgbP9texH2N3Q=,tag:0BNFkmrDouGpVXhSD6uaMA==,type:str]
    ROCKET_DB_PASS: ENC[AES256_GCM,data:weMTjvX7Qte8cw==,iv:GZBWud24QTfE7NbVFvAae2GvPBFIM38hzBpiB+HWu7E=,tag:5X00wLo2fpJ/1PGH1K+I7g==,type:str]
    SECRET_AUTHENTIK_POSTGRES_PASSWORD: ENC[AES256_GCM,data:/NS1HyapxJAIxCNRp0CAzGbOduFK,iv:gQ/hZzl15BJ+ElNFvaIaW8WkMxNapDsPb9/1NakrPEY=,tag:glBc+zRmtthho4MYXrK5wQ==,type:str]
    SECRET_AUTHENTIK_REDIS_PASSWORD: ENC[AES256_GCM,data:4sT1gno+BcRvrbJMXAQqiN/x,iv:8OP9+1iRJawBHS/Msgrw0ddYSPySXywLJVNXGned0Lo=,tag:Bp2reBabZvQ1dNTO65cpAA==,type:str]
    SECRET_VPN_CITY: ENC[AES256_GCM,data:YUzP2i4ERsg=,iv:kxZ90iLFOM8flWBc1eQFAibAqrDO1xYS89hrhbFXHuU=,tag:XKX/9Je7C7nhnrST9eNsdw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pqmv9umk70z2xyv8vvlma070d9rzr02j3ye8gjyv64ddf0sfwccspwsj8d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvOERSUmFwcncyUXlxYlBm
            anZCcTZrNklxL2tkUDhyaUVJOXZJbW9oZG5NClZwN1VmWDJzSGlPcEtBRUlHcW1p
            bE1PNXlzS1lvRVd4T0FVbk1sdGlDOTAKLS0tIG1YOXNybEpGK1ZHeWMyUUllUTRw
            QklkK2FPMWhOYmhKSlhMUDVZczN1c3cKdXfPDzIwz2QqmyshYQWxmlhBaofYXj0m
            0uJiDFJcIDpse9UynYvT/tYPzOsb/OoVjnEZp2EXReSLGTNaIiKTeQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-16T03:15:54Z"
    mac: ENC[AES256_GCM,data:w6sv/mOkrL5mdt4CLqfnaJiRgf4K1KffD7l0O6Vud8AskCQpaesaDQuTw5Et077LUHHErWzxqoRqPJr75lxnWovzMsdZCc6Gak22RKt1s/9VTOgDDgsJG2LPOhkMREi/4Pyirriez9Z2RravkraeJ07QEEuwwu8Ej1yuUwv7CEg=,iv:F9feghQjp5fmSaXZGaA4ZpTEY/q/D0eoZx7AAiKF3oI=,tag:TM3utwSVY6fQAHByBIgxjA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
