apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EMAIL: ENC[AES256_GCM,data:2ghhnoFDAIoEEEfSP0JfPdz2,iv:iqL/Ar1/EH6LzYGAzQUDE4QhLg0xiNIUIsj3+JKF1ng=,tag:JwSA3szVw0jT+MagVF0+Vw==,type:str]
    IPINFO_TOKEN: ENC[AES256_GCM,data:9yRpBc+lxylj1wsSV7o=,iv:okw1KGkP03gSDtCrVDO1TSF4J7ZuFKqqZdpf12q2mCM=,tag:7W/p/NVsZcHftN/X3CVRhw==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:lieXi1YTv2L43SdubnI=,iv:opwyLLPCJAWrHNd1Z/bMV1ghCBEpzx14Q0TOfzR9lVM=,tag:5QNPUczvrFTBWujWoLl4Xw==,type:str]
    SECRET_DOMAIN2: ENC[AES256_GCM,data:n8rbSLlN58/X2mrd3A==,iv:kacDY2SC7XMUoK2d5aJg95JRkh+xpu0fvLSfDFs6zqQ=,tag:F/lv7jMmzWZ1zFWfWywB1g==,type:str]
    SECRET_DOMAIN3: ENC[AES256_GCM,data:kwJR2fH2QaIvGZ5vOnE=,iv:jv3m9MxZJCr1ySTIxpcXkNP5ZTpmB0w5xh08nvwhXzI=,tag:6A9aBsdbuZf/088LkWkBdg==,type:str]
    INTERNAL_DOMAIN: ENC[AES256_GCM,data:2qJfrvVRVJbblT+UNY1tKZm36g==,iv:S3EG8C1PaGvrSVYUYkb5PC37iAC5kd/eikWwKHpewh0=,tag:vvh01GDnQLFGmkKUJw1YUQ==,type:str]
    VALHEIM_SERVER: ENC[AES256_GCM,data:UUKs/8eB9oxsUfZq,iv:pC9ShElcoiBfQZx48LxkEk4rcZAdztUhOlToYwt62UE=,tag:tkYPp/EkSK5NSx11rIfPXA==,type:str]
    VALHEIM_WORLD: ENC[AES256_GCM,data:/dOkEMhmqqq7mqhj,iv:iHV+07FHuMfLHt9bsgjEHYeKYbhGRGBwrLUl7x8mE1Q=,tag:vEmdr+esycGrek4PB4Boug==,type:str]
    VALHEIM_PASS: ENC[AES256_GCM,data:C9BbwK/ybOo=,iv:tPi75pjzaZEZ29XuI13Ef/YrD7wqwQVCyJxzy7uSSg4=,tag:PuX4xcrqDwGiSufAIYtWlg==,type:str]
    SUPERVISOR_PASS: ENC[AES256_GCM,data:67UtnqJxepQ1,iv:Z8WmiNdZoYnU8pX/0aDdRfUBn0+yj7ge83TpGE4GP90=,tag:wBoS7srd0h5Av1m8beIEWg==,type:str]
    LOKI_MINIO_ACCESS_KEY: ENC[AES256_GCM,data:cN7Dz5Mtl5Vk/1eKhA==,iv:UzSxYsUjaF8bJ13IQzZsCrdZtcpyFo144QHsFFFZzXU=,tag:7djZNPYceHn142cue+IooA==,type:str]
    LOKI_MINIO_SECRET_KEY: ENC[AES256_GCM,data:Ie6LM3ig3TR1M5OLjT6P6EZwBp0BHt3x,iv:DDp8XMdvPGBFIlq/p4s9rGxU5BPLH/mHCHC9weegYrs=,tag:R614jypx7FXNsUFnfL2TYw==,type:str]
    SECRET_PASSWORD: ENC[AES256_GCM,data:b7k/XCS5ie1J,iv:L5u09NSt9Vv7FknOyNuMIsOZZeXcuazvsJ7ZtwvG0wU=,tag:SH1+lwW0Lj/dFSh7hD2KLg==,type:str]
    SECRET_POSTGRESQL_KUBE_POSTGRES_PASSWORD: ENC[AES256_GCM,data:ehkZQrGTZrmd,iv:CrI4Hq1jlMKXWqv1XU58lpwKDVz2V55IArZRm0OW6rI=,tag:OygW+Fk/0F4SwkOEuBVY7w==,type:str]
    SECRET_REDIS_PASSWORD: ENC[AES256_GCM,data:z1Ar9CH+a/49,iv:dZnWIIdznVZfHAYQSbB1IKlMaMF47oHwDeatVwbRVxI=,tag:+B0taWtCwoXonFJgZih/HA==,type:str]
    VALHEIM_DISCORD: ENC[AES256_GCM,data:mcLvY+gbv0IuNSaVZLP3ypY7d6GmeDMLBabRnQnQCQGU3Khk+yVo/LS4x6/WDp+wVnfvVnPhP8cb7tCMf/8O63ZB+g7C17+0sepI7tt3m/GBAbJ9JSsxyCqDP0aW3nrXsyZNiewdJaFHHfpV5FhmMWF+lhSa6Lxj,iv:NYl6V8rsopeps7byOLSg4lVRcWgM2VrzWNskLDgxKNw=,tag:Borx36qINe8u+lKAuHAZ7g==,type:str]
    VELERO_ACCESS_KEY: ENC[AES256_GCM,data:GZQ3zUMG,iv:6RwhF63S/BhSCRwCZgPsvRUdgsQS15yRq9+1j7d+42k=,tag:qdFxaE0yibJ0mUjQkDUEXQ==,type:str]
    VELERO_SECRET: ENC[AES256_GCM,data:FWsk+L9SwgDUIkq9611nSt3E0qjoIWTuW3s=,iv:7TQsDgax10Im8qfwTCHXtdqKvQiX+wf9cu8fIRm4XC4=,tag:h11O5aOJRDbmSqO0u8h4Ew==,type:str]
    AUTHELIA_SECRET_PASS: ENC[AES256_GCM,data:Gc0L46pG8H67mQAbgl4BSJjg/niqE+5Cq/3JduSn/deDx6j8JkmsLytjBqOvPzuRLtXQGwny5tUnCCaBbXBGhw1OacaMyadDrUngpprG8RTiVOKNvWzM4Bbfs6Fpo1q/Tw==,iv:rHjBdLv47ZlcG6B65455zKi4mzPDyPJPlgnokV0rpPw=,tag:Lca7vQl3oha6q39kqmBGaQ==,type:str]
    SAM_AUTHELIA_PASS: ENC[AES256_GCM,data:r8UFVZLEPP3XP01s5y1hNjhbl4Qw/c6mV4DVwvd17DFDZbdlVn7Th3DdRmQothSFbM/NulyKf8+bml3Wf6nqZ1xWU15R5uN4/4AFGb111SeM++x/NxLOE9Q1hjLZfCAfXg==,iv:icqXA9b/CWz3CclYM295W/clnKPN6NmyfWfO9jRo82Y=,tag:wObVi6mWInvXZME5BrsrAQ==,type:str]
    SAM_EMAIL: ENC[AES256_GCM,data:XT9mvqE0G4vheooMDai2F2ROZQ==,iv:WpH3TJFMShfSKGnBhwKer++RPqqgLhuWGgQwNtLBhus=,tag:7XDmkGh8K+AcO7Vg4c9myQ==,type:str]
    SECRET_AUTHELIA_SMTP_PASSWORD: ENC[AES256_GCM,data:bPbf8VxDBQI6PfpOyeNTBg==,iv:f/zG9Jjp1xPnQ4LfPz2IncFTIMCSn5B8u2C+O6jrYxg=,tag:q+JfpWqyoFDo38ZjdldpGA==,type:str]
    AUTHENTIK_KEY: ENC[AES256_GCM,data:LPx4Es9C/O9pWpY87Wo8n8Nv/XXgQLW13iG8deJqMeLmil1g/s/D6SjYjhQWPWFn99U=,iv:s+HCwBSqFsR5OIonu2amlfGdiZiODr2/yOA1KIy2maU=,tag:jKpBXJvgPtKets8B2FQjhw==,type:str]
    ROCKET_DB_ROOT: ENC[AES256_GCM,data:zQcRZDsZUNAKrg==,iv:m/mcfYW5N31wF2p6QwdYzHa5vZqVk1LX1CPpxn7f1j0=,tag:sezdb2ujtcIe5HmU3Jl5NQ==,type:str]
    ROCKET_DB_USR: ENC[AES256_GCM,data:D66jo+7OaUwI8A==,iv:1DcB9DnRzqpouQCBGo8KWTGypLUbRLwnNLnlwFDHa9M=,tag:OjAbtvuJV/j0S+vbAD5QiA==,type:str]
    ROCKET_DB_PASS: ENC[AES256_GCM,data:wNDJL7hNtz17XQ==,iv:yvo7MREEtWIfbDhV9YlpdJpz55sysFU4MN4QB/F0S8Y=,tag:XlifhmOCVI9jGZXfQL+KcQ==,type:str]
    SECRET_AUTHENTIK_POSTGRES_PASSWORD: ENC[AES256_GCM,data:MEh4BQ+0x3R3X7qK3KuwLbUrSa77,iv:aLjt/Bhl0w0+j6t7RhLeUribyfpN8ctfZz/qmYXzlbs=,tag:9lo3IXqJRPm7aAyN3cpbIA==,type:str]
    SECRET_AUTHENTIK_REDIS_PASSWORD: ENC[AES256_GCM,data:WZ7QSugatj0sFxb4AzUUciJZ,iv:OQslULD+xfVeITjZUiiCq9eORCrfvRPvfz8hlQkoGJE=,tag:fjWnpm8L93yoDmhZ+Aufdw==,type:str]
    SECRET_VPN_CITY: ENC[AES256_GCM,data:/ffJIkWMMqA=,iv:s0hFTOekdGuCZ8F2jHZjPrV4fjHzuo+xTX5esg1xJvA=,tag:wmuTE8peyPmpUFvHAPV8Ow==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pqmv9umk70z2xyv8vvlma070d9rzr02j3ye8gjyv64ddf0sfwccspwsj8d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSZ0NzTmh3YkF6SDBmcEVU
            N1BOanFjb2V1VVUyc2FvTzd6aVZVUGk5THhZCnZuVFZrTEc0Sk12MXBuL1VpRTBP
            Ui8xbEtuaXVPM1N3L2F0c2ZWaHhKdTAKLS0tIFlDMHdoc2c1VEdMVituN3JjQXVz
            SjBYTHZhVWxJOE9NYmFNNHl5TGh6NGMKi2W+XNEXH9NBvb/y6Qysea7rKABpCSVp
            B58kpzl1pGroqLj/fTZee5ry/3Te+oymGu4Lqokgp35F8pWBJjXC7g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-13T02:30:25Z"
    mac: ENC[AES256_GCM,data:ApTL6mcxoVEATVILRygeWSvtlRA6ov1+NMWNZ4BerDII+e9a3Acm9OTGttaKJjIChHEaX4WSS+j4SHry2UUjALPIeohB2bQgN4A50adag2n7zR3eYFHWu0TRDjETGvCsogmNBRabEgQJW17vppZh9QsxTQ69YUmJVHpDEePpcP8=,iv:CI+3niSMpK2jxVjRSEpA1VCkgeente5wIEVPa//Uj0A=,tag:Jn8EJjKK2xJw5/in+zr6KA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
