---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: unifi-poller
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: unifi-poller
      version: 10.1.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/k8s-at-home/unpoller
      tag: 2.1.3
    env:
      TZ: "America/New_York"
      UP_UNIFI_DEFAULT_ROLE: "home-controller"
      UP_UNIFI_DEFAULT_URL: "https://192.168.1.182"
      UP_UNIFI_DEFAULT_VERIFY_SSL: false
      UP_UNIFI_DEFAULT_USER: "unifipoller"
      UP_UNIFI_DEFAULT_PASS: "Unifipoller1"
      UP_UNIFI_DEFAULT_SAVE_SITES: true
      UP_UNIFI_DEFAULT_SAVE_DPI: true
      UP_INFLUXDB_DISABLE: true
      UP_PROMETHEUS_DISABLE: false
      UP_PROMETHEUS_NAMESPACE: "monitoring"
    metrics:
      enabled: true
      serviceMonitor:
        interval: 1m
        scrapeTimeout: 30s
      prometheusRule:
        enabled: true
    ingress:
      enabled: true
      ingressClassName: "nginx"
      annotations:
        kubernetes.io/ingress.class: "nginx"
      hosts:
        - host: "unifi.${INTERNAL_DOMAIN}"
          paths:
            - /
      tls:
        - hosts:
            - "unifi.${INTERNAL_DOMAIN}"