apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - authentik
  #- authelia.yaml
  - cert-manager.yaml
  - metallb.yaml
  - k8s-dashboard.yaml
  - longhorn.yaml
  - networking.yaml
  - external-dns.yaml
  - ingress-nginx.yaml
  - media.yaml
  - downloads.yaml
  - vpn-gateway.yaml
  - monitoring.yaml
  - gaming.yaml
  #- rook-ceph.yaml
  #- data.yaml
  - hashicorp.yaml
  - security.yaml