---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: consul
  namespace: hashicorp
spec:
  interval: 5m
  chart:
    spec:
      chart: consul
      version: 0.18.0
      sourceRef:
        kind: HelmRepository
        name: hashicorp-charts
        namespace: flux-system
      interval: 5m
  values:

    global:
      image: "hashicorp/consul:1.11.1"
      imageK8S: "hashicorp/consul-k8s:0.26.0"
      datacenter: dc1

      server:
        replicas: 3
        enabled: "true"
      ports:
        serflan:
          port: 8301
      storage: 100Gi
      storageClass: longhorn
      ingress:
        enabled: true
        ingressClassName: nginx
        pathType: Prefix
        hosts:
          - host: consul.${INTERNAL_DOMAIN}
            paths:
              - /
        tls:
          - secretName: secret-consul-tls
          - hosts:
              - consul.${INTERNAL_DOMAIN}




