---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: argo-events
  namespace: dev
spec:
  interval: 5m
  chart:
    spec:
      chart: argo-events
      version: 0.9.4
      sourceRef:
        kind: HelmRepository
        name: argo-charts
        namespace: flux-system
      interval: 5m

  values:

    registry: quay.io
    imagePullPolicy: IfNotPresent
    serviceAccount: argo-events-sa

    additionalServiceAccountRules:
    - apiGroups:
        - apiextensions.k8s.io
      verbs:
        - create
        - delete
        - deletecollection
        - get
        - list
        - patch
        - update
        - watch
      resources:
        - customresourcedefinitions

    
    singleNamespace: true

    # sensor controller
    sensorController:
      # -- Sensor controller name
      name: sensor-controller
      # -- Repository to use for the sensor controller
      image: argoproj/argo-events
      # -- Overrides the image tag
      # @default -- `""` (default is the chart appVersion)
      tag: ""
      # -- The number of sensor controller pods to run
      replicaCount: 1
      # -- Additional environment variables to pass to sensor controller
      extraEnv: []
        # - name: DEBUG_LOG
        #   value: "true"
      
      sensorImage: argoproj/argo-events

    eventsourceController:
      name: eventsource-controller
      image: argoproj/argo-events
      eventsourceImage: argoproj/argo-events

    eventbusController:
      name: eventbus-controller
      image: argoproj/argo-events
      natsStreamingImage: nats-streaming:0.22.1
      natsMetricsExporterImage: natsio/prometheus-nats-exporter:0.8.0

    securityContext:
      runAsNonRoot: true
      runAsUser: 9731