---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sabnzbd-config-v3
  namespace: downloads
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
  storageClassName: longhorn
