---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pvc-v1
  namespace: home
  labels:
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn