---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nzbget-config-v2
  namespace: downloads
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
  storageClassName: longhorn