apiVersion: v1
kind: Secret
metadata:
    name: postgresql
    namespace: dev
stringData:
    postgresql-password: ENC[AES256_GCM,data:6DZ/83TuhkMbug==,iv:5sOnLVq/bo5y9g0+gK9hxqtOlyOFfAvG67WsIM2cThw=,tag:ZJaBFXX2zER7RALjkikkkA==,type:str]
    repmgr-password: ENC[AES256_GCM,data:kLYhd0JnmmJ5Qw==,iv:mxU5dfegHhixwCQiIXDsI2UXhTSv7AN2MrYltq4z+po=,tag:+fxfxEnGbzBwa1tQZwmKiA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pqmv9umk70z2xyv8vvlma070d9rzr02j3ye8gjyv64ddf0sfwccspwsj8d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQYjkzSGk0c0J2bjMrVHlS
            SVEzOElLaVhiS0pPd2lZL2poQ2plV3RVWmljCmlpeHJHYjlFSXpUQ1VNY1RrVm45
            eUZXRFNsNEV3Z1hUZ3p3bGxyY25HTEUKLS0tIFo4QUZCYWJVaFBLM2Jpbjg1bmJt
            dmNTNFRhYVBwVEZJMC9WODJBbkRxLzAK4YNGexAic0sYqMu7KEGFgMqW51RX0MNX
            q/6v7FphARo9UQDc69r/mAbFfJFIyp++fjk8/d6/gPNR9YtVQNX0Ow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-21T22:22:21Z"
    mac: ENC[AES256_GCM,data:uAUflrRnZT5NVZxRAxeO+Q5rJwvwCcGt+sOP9YvYUgPdYGE/N6HfO1mIi/+Tv0bYC8gDTflQ4e4hAoBRVNhk0rRmnBwOEqWDZeEdf6krxS0tgiRQhvyy2XbabgtzNCu1XI+0OSQG4fAsxjA/MonVkoZNS+ykZ0sn8Su0jQC/oo4=,iv:tz6STfxZPQsPUQk/zvqBu/xIXxpo6VS05YXu+DBErHQ=,tag:+ySLLiVoZIrhvAxRb84+Yw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
