---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgresql
  namespace: dev
spec:
  interval: 5m
  chart:
    spec:
      chart: postgresql-ha
      version: 1.10.3
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 5m
  values:
    global:
      storageClass: longhorn

    rbac:
      create: true

    postgresqlImage:
      registry: docker.io
      repository: bitnami/postgresql-repmgr
      tag: 11.14.0-debian-10-r59
      pullPolicy: IfNotPresent
   
    postgresql:
      replicaCount: 3
      updateStrategyType: RollingUpdate
      containerPort: 5432
      securityContext:
        enabled: true
        fsGroup: 1001
      containerSecurityContext:
        enabled: true
        runAsUser: 1001

      database: argo_workflows
      existingSecret: postgresql

    pgpoolImage:
      registry: docker.io
      repository: bitnami/pgpool
      tag: 4.3.0-debian-10-r1
      pullPolicy: IfNotPresent