apiVersion: v1
kind: Secret
metadata:
    name: thanos-objstore
    namespace: monitoring
stringData:
    objstore.yml: ENC[AES256_GCM,data:emZNhtbALTqb9SSO+ruHnjTNC+jUMhKDm6U7IIn+Cl5rsgE3yZzmq53in8StdrNkry4I52ztvbGXmZnnxbsYR7iZMGTzrZQILA9pEFXuUTE0zHmPGEiqOv1gT2pBvz8bPYxKgGuu+brUpplhon8INl8TZvRWHozeIwtRAJpe2djyTnaiFPEwbVwUI92ifu6iPKvYn/4tzR1IcZQU6/bX16T25IaUFE/gXx6vrReqOF8t1hkCIq2Qb38Bwg2MELwMeNSSHIVPAoyYWIL/4d/Atv/QB+Ud4s8k1MnkK1rzlwMNJQQG8iHzfm63zwZT6M3FrvDMGw/9AzFUcjVryQ==,iv:BGR7Ot4yGDOZl32lTDpgKeJ/GtRCvBxMPv9CVc3Nq/k=,tag:+XguF9GaSGlOBDQopaFzwQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pqmv9umk70z2xyv8vvlma070d9rzr02j3ye8gjyv64ddf0sfwccspwsj8d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHUUNDTWR1RUV0Z0hLanFJ
            M0h2enBtYkVuVml2UUIwY3JZUi9UMktPV2lvCndGTFRLK1Y4Q2pVdmIzT050WXhB
            SG9sUHVOZnJ4OGl6aGR0SUpqTGxLT2cKLS0tIGZMbCtQK01IMDBpY2pyRnRKbmhw
            eFlnVDNyUmR1WlZzUkdURXNHYmgwUk0KEMAru/J4zWAWJLGKbQ0Dwg13MWqG9hRh
            9bdr0RFCqRUkt8lv+W03UVPKXx0BJHtWG6j9TVq26esEgFJ30R+Dkg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-25T18:01:41Z"
    mac: ENC[AES256_GCM,data:FSo9A5zyAAx8wmO+6+Cf+wsZXTEjEE1dgZwqBO0mC6/C/yhGCKXpaLS2JSEiqKZnmimW18zXhhWICvVnAhK+TDqy+zlQ2cU9TLcX1LRDClvZl3MUjNCk9YnvR2SWf8281OlobB/zFwdEb2unZbOz7DidIHn1IoCsmZALB/7o65c=,iv:zvLGkQ0gBGdr5TE0n+uqblzBrIXcWFB2vDDQ9ebYzCs=,tag:VP2QFyLPgH8LxeGmOyHTbQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
