---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: plex-cluster
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: plex
      version: 6.1.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: lscr.io/linuxserver/plex
      tag: latest
    env:
      TZ: "America/New_York"
      ADVERTISE_IP: "http://${PLEX_LB}:32410/"
      ALLOWED_NETWORKS: "10.0.0.0/8,172.16.0.0/16,192.168.0.0/16"
    podSecurityContext:
      supplementalGroups:
        - 44
        - 109
    service:
      main:
        enabled: true
        type: LoadBalancer
        loadBalancerIP: ${PLEX_LB}
        externalTrafficPolicy: Local
        ports:
          http:
            port: 32410
            targetPort: 32400
            protocol: TCP
    ingress:
      main:
        enabled: false
        ingressClassName: "nginx"
        annotations:
          nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
        hosts:
          - host: "plex.${INTERNAL_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "plex.${INTERNAL_DOMAIN}"
    persistence:
      config:
        enabled: true
        existingClaim: plex-config
      media:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "${NAS1_ADDR}"
            path: /volume1/Media
        mountPath: /media
        readOnly: true
      media2:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "${NAS2_ADDR}"
            path: /volume1/Media2
        mountPath: /media2
        readOnly: true
      transcode:
        enabled: true
        type: emptyDir
        medium: Memory
    resources:
      requests:
        gpu.intel.com/i915: 1
        cpu: 1000m
        memory: 1000Mi
      limits:
        gpu.intel.com/i915: 1
        memory: 32000Mi
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: feature.node.kubernetes.io/custom-intel-gpu
                  operator: In
                  values:
                    - "true"
    podAnnotations:
      configmap.reloader.stakater.com/reload: "plex-promtail"
    addons:
      promtail:
        enabled: true
        image:
          repository: ghcr.io/k8s-at-home/promtail
          tag: v2.4.1
        loki: http://loki.monitoring.svc.cluster.local:3100/loki/api/v1/push
        logs:
          - name: promtail/plex
            path: "/config/Library/Application Support/Plex Media Server/Logs/*.log"
          - name: promtail/plex/plugins
            path: "/config/Library/Application Support/Plex Media Server/Logs/PMS Plugin Logs/*.log"
        volumeMounts:
          - name: config
            mountPath: /config
            readOnly: true
        securityContext:
          runAsUser: 0