---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: plex-cluster
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: plex
      version: 6.1.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/k8s-at-home/plex
      tag: v1.25.1.5286-34f965be8
    env:
      TZ: "America/New_York"
    podSecurityContext:
      supplementalGroups:
        - 44
        - 109
      fsGroup: 0
    service:
      main:
        enabled: true
        type: LoadBalancer
        loadBalancerIP: ${PLEX_LB}
        externalTrafficPolicy: Local
        ports:
          http:
            port: 32410
            targetPort: 32400
            protocol: TCP
    ingress:
      main:
        enabled: false
        ingressClassName: "nginx"
        annotations:
          nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
        hosts:
          - host: "plex.${INTERNAL_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "plex.${INTERNAL_DOMAIN}"
    persistence:
      config:
        enabled: true
        existingClaim: plex-config
      media:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "${NAS1_ADDR}"
            path: /volume1/Media
        mountPath: /media
        readOnly: true
      media2:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "${NAS2_ADDR}"
            path: /volume1/Media2
        mountPath: /media2
        readOnly: true
      transcode:
        enabled: true
        type: emptyDir
        medium: Memory
    resources:
      requests:
        gpu.intel.com/i915: 1
        cpu: 1000m
        memory: 1000Mi
      limits:
        gpu.intel.com/i915: 1
        memory: 16000Mi
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: feature.node.kubernetes.io/custom-intel-gpu
                  operator: In
                  values:
                    - "true"