apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:WRm24Vh3DDhbaRdDtmo=,iv:eWPOH5q5at1y7Wny0tQSXzFbSn5DMRMGe7752ZMIGGw=,tag:t0ycwvlfuaByc9Bnqsar9Q==,type:str]
    INTERNAL_DOMAIN: ENC[AES256_GCM,data:J7VBpfGQ5T8pSOBlgUYlVsB6zQ==,iv:FUrEAY1n01bFnvWpmfr2GwmS87AxjfhnqVMmCZPsgXc=,tag:P3WZptS1NQmVpLti411WnQ==,type:str]
    SECRET_PASSWORD: ENC[AES256_GCM,data:pyoCuwY0L7bQ,iv:bRlPQ4o3/8L84nbfrP0itaRMekWqBGxRXDxPo4NmNc0=,tag:/er7Oy8nXTfaEJWBiq0a7A==,type:str]
    VALHEIM_PASS: ENC[AES256_GCM,data:RQIvga5lZ/Q=,iv:w27Fg3fF4ieivg5jSvakbHIlIOZaL+b3fGFQVWMUOTM=,tag:qhnT/DXH2Q47tSO3QHB5gw==,type:str]
    VALHEIM_WORLD: ENC[AES256_GCM,data:9HaZO1af39vmXgOu,iv:ejpg1hYs6n+xH7/UPbe5gPcizZ46AJmfisQMbJf+6Jw=,tag:rk797tJDXhPmTlbwMXS/dw==,type:str]
    VALHEIM_SERVER: ENC[AES256_GCM,data:WO0shnQyMmecniM=,iv:HqpKyXPbjUQ3rleDAw/mrU2vWGU1qjjxnqsdRi8ArjY=,tag:Bq0Jdfw0BKORE03I2Ji/FA==,type:str]
    PLEX_CLAIM: ENC[AES256_GCM,data:PZzGL6L9+rily+mpDH26s96wWfGetL65itI=,iv:gxkYJ3Sez//GZFV9C/WVYMKGRraHWP5eyoncfyz8c6g=,tag:4AmA3efk6HRgdwv3YLbxtQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kmn982kderhq3468sre0cq9y93qmw4m4wk9eh5288a0reaa4xsrqpf0s9x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhc1RXSGJrYTdORll0SWVh
            YjBuV0pQaDVaVEdzQ2Y5RDJ4TGw1NU9LdEg0CjJZb3VTRTU0VmJheEMrUVJZRUE2
            eWRYR05lWlZFZ25YRS9nSnNzNS9BWjAKLS0tIHVDNTZldlRoUDNSbVk2WGF5UHlR
            dHZEamh6Z3RocFhHOURIQ24wTHNSb0UKs+QAzT6a2n8K0WigsWNKgpS/6QlCdAF1
            f8Qtt+K20p64o3AmCDKPDe7fco6g/jkUWMF8NriQCPZEQglTCQt0iw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-10T15:21:56Z"
    mac: ENC[AES256_GCM,data:qThDJPOOwdnE/E4pht+kNOc+1WiNu0IMmPCwMJDZfsL8BeOBGIY10H2TaXrJfYMPpwe07YQjXrM7wI7WNu0jPGSjV151aWtrIBK3QQ8fgcMxD8Ndq+zMiu2vTJVcrY+Vz+72M7KwyR/1CnRHHvlWvKPSrh9xlYLDoZ5BKtMimDc=,iv:6382Qph9SgpO/PZHsqJWeMOcI6PtBdHJvoYOjulWV4w=,tag:FntYP3nBcl1CWJPZMbs0Ag==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
