---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: flux-system
  name: cluster-settings
data:
  METALLB_ADDR_RANGE: 192.168.2.50-192.168.2.99
  VPN_PORT: "51820"
  VPN_GATEWAY_VPN_PORT: "51820"
  VPN_FORWARDED_PORT_1: "59494"
  VPN_COUNTRY: CA
  NETWORK_K8S_CLUSTER_CIDR: "10.42.0.0/16"
  NETWORK_K8S_SERVICE_CIDR: "10.43.0.0/16"
  NETWORK_MANAGEMENT_CIDR: "192.168.0.0/16"
  NETWORK_SERVER_CIDR: "192.168.0.0/16"
  NETWORK_GUEST_CIDR: "192.168.0.0/16"
  GATEWAY_ADDR: 192.168.1.1
  PLEX_LB: "192.168.2.99"
  SVC_SYSLOG_ADDR: "192.168.2.98"
  NAS1_ADDR: 192.168.1.177
  NAS2_ADDR: 192.168.1.200