apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EMAIL: ENC[AES256_GCM,data:Mpvtrc1ykFqgj82b04k86JBD,iv:qR7FAxgasrcSXK3a8AEMyCMIN2iwtahsY+dGmQbl1VY=,tag:HF+4Fm8YJMN589QHSy2YSg==,type:str]
    IPINFO_TOKEN: ENC[AES256_GCM,data:75GvgEqntHV0T2W4B80=,iv:RHivMu4lfeSYCUH4PQTAxe3Oe8ExyxUsXgPxPzQ4cV0=,tag:otaqkQBHcwo6OeqNZc2z0A==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:23owzCpkyHKfWYVKNtQ=,iv:acUzHqfjUzLt718Ti5Nrww6uhkXOA5rsHTkU17owcFo=,tag:UcGjLoSXBW8gYQY3GbDFPw==,type:str]
    INTERNAL_DOMAIN: ENC[AES256_GCM,data:rxrIFeDSnBTmOgeiH8/T6/+wGA==,iv:Dy+j/Moey2W3ryHGHZVP1uarE+caHkAzv5xVeFR+Qlo=,tag:+L2FwD+5YLbRY+oHJXq2KQ==,type:str]
    VALHEIM_SERVER: ENC[AES256_GCM,data:fVIiVZKtYKbELcL0,iv:utjGsQyKFq7BBTLNISuVCTKlM5nnw+t9lAykR/dhJv8=,tag:kSgXzxVc78h0c28SD9qpTA==,type:str]
    VALHEIM_WORLD: ENC[AES256_GCM,data:4QVKplTKWVJ6VCLN,iv:McUVd2LHfvEmb1CyQ5AczgTw+8dGsycltyfeBafkmu8=,tag:olLMFz63F45j/IQOnfQAlQ==,type:str]
    VALHEIM_PASS: ENC[AES256_GCM,data:tXeAcIsJdXI=,iv:bLL7uSMGCvDHcjfOiuqnhrNgvUNubcjbLb611VFauPo=,tag:Uypw6qRP77GbHVH+TF7o/Q==,type:str]
    SUPERVISOR_PASS: ENC[AES256_GCM,data:Y4YrCj1K35br,iv:HcET/rz8nL0QOx+aofR8UIfCN0WBUzp/R5WcpBJbyHw=,tag:QUTCpOnvx116f7ljvC2Kuw==,type:str]
    LOKI_MINIO_ACCESS_KEY: ENC[AES256_GCM,data:V1GRhmua7ILF3MRTgw==,iv:f+EvqJ4sJs9PnClVhCQm31nnkHQq2eK/UgPCcb6Bkm0=,tag:9F50RzrbDw9KqcmSGxZ2Dw==,type:str]
    LOKI_MINIO_SECRET_KEY: ENC[AES256_GCM,data:OR18fOYl93J8vqHpIy2+j1rp6hrKIuKt,iv:R38KJITEpPMPkJpE0o+ctA0MyMJxzE29JxIPB4eyMZY=,tag:YZoFmt+B9HHlXUWeMzUNRA==,type:str]
    SECRET_PASSWORD: ENC[AES256_GCM,data:iBSRr+58TPKi,iv:4e0dPflLghMXeP2sC3+zJdwnhEZXbgv/gUf005i3ilM=,tag:R7+H0jKzqz67toOh2QzMhg==,type:str]
    SECRET_POSTGRESQL_KUBE_POSTGRES_PASSWORD: ENC[AES256_GCM,data:4gcf9azinLxE,iv:te/MovBAeQ8T46MjfRy26k0RQoA9oDdaXuUyqz9D7tU=,tag:aR8AKd6Xhy7Tcw//Bo7hQg==,type:str]
    SECRET_REDIS_PASSWORD: ENC[AES256_GCM,data:ZZcjrC4nFjoM,iv:/F2W+iNRp/yx0fbMP3uKoR04uhi+UEkFBLQ2KMrOYnw=,tag:lEKh3dv2DP9NgDiMT5nHkg==,type:str]
    VALHEIM_DISCORD: ENC[AES256_GCM,data:10r6ZqupuClEbVju3Vjl5mLgYqE0tHFBikx03V9KatotTh9QIiycwyvjGVzmb6MciD9WAxUuB46RrANmregJIO3tCEM5QJB6ndaS0FD/pHdkJarM/oTEaeyK7/j3tFkT2hycQIRkefvIJFQiXyC0er3MIeiuR666,iv:0cmqokcmgSjiOVt5an/q3LVQwZ0998rzFvgpaj6pq5c=,tag:R7XKlpM7Ev5agQv1Q8zDqw==,type:str]
    VELERO_ACCESS_KEY: ENC[AES256_GCM,data:v2zfB8pD,iv:DH0sdxEw1VP6kbPiDkArW1pRdVkhuUSmaZJvwK3BSXg=,tag:S05S5EU0SGg2IesUuys9/A==,type:str]
    VELERO_SECRET: ENC[AES256_GCM,data:78XrtVrvpfba3dLZZy9uM5wC0bF3Smk8VwI=,iv:vk5lX0bJUEjSPQwjU98pYld9/jxtyAgHAN2CS5u9O28=,tag:RZuapjMReiOYFbIxgyLsxg==,type:str]
    AUTHELIA_SECRET_PASS: ENC[AES256_GCM,data:F5jobl3ehHEb3THk2wyV+j5VUs2visvhBoXVdVfGRhfc6cxU7R/banzrCK9GCbDbeUC3NS06YXxbYg1DKhV2QNtTMjj3q8vJnQDkz7wmHI5VdJaAfkJR+g28SQVkd3E5cQ==,iv:H0wl5JVGQPdJBfIjdA+3kTmM8u1eXmbWhT+xTXIUdxE=,tag:95s+2IIJyxH17U8jpeC3eg==,type:str]
    SAM_AUTHELIA_PASS: ENC[AES256_GCM,data:kv7GrLfXqnozh/VhGX8DZyKnXm8EaDd4rSYHAQqoMsa0Kpx01TwMeenx7UP6aI4OOgChjfohiZfJ6Ib1L5In4JSNE9zL5QF6lwbfR+PkaPomf7ybivQShtU6JeZRL/OvUQ==,iv:W8Ew0poMR+y/9mPSPSxlGC8cW6+uda24pvxinmyNOkQ=,tag:5QqsJob8cvqVnR4CpOr7Kg==,type:str]
    SAM_EMAIL: ENC[AES256_GCM,data:uqA2LPmMAMuURcmDFXymq2Yhog==,iv:FZl3gZ68DRqfzRKk8gkKBtGwPtnQp+t9FjWD1OlXWNY=,tag:g4++oturGwT2K+fSPZopnw==,type:str]
    SECRET_AUTHELIA_SMTP_PASSWORD: ENC[AES256_GCM,data:UQp1UQ7oV3tYbRFJ6Z95Cw==,iv:Eyf+zFdgmSW/foBJHYu2vdsnMzaMr1MrfTmlnLthQ+c=,tag:YMfRidhU3WzggizbmLTOGw==,type:str]
    AUTHENTIK_KEY: ENC[AES256_GCM,data:jI1FbkuRZnuw7aiWb5/Z43gLRUJ1bIp9qVB3oCbWFo2OMHPxSuCMuPeDP4G4WgXFA1w=,iv:k2dVbmQqzzHY85R75MbM9tmSMeaz6t+drKS9TmIWZrY=,tag:/x+o/HuKex1CLF7J7tFzKQ==,type:str]
    ROCKET_DB_USR: ENC[AES256_GCM,data:Ie0Q4oK5zQELVw==,iv:e5NlFOJfXTZ9ika/+NbXUqHXrd9PGwsM2BLN8M70dzk=,tag:jG1NvN6a5d5SIXCikqeOnQ==,type:str]
    ROCKET_DB_PASS: ENC[AES256_GCM,data:v6R16/KzBSWaXw==,iv:lbRkS98Hvur4f1nWZCClWCT6xSML9onRh3sKkBbFqPI=,tag:oisUxRXEchdk5bEOeiz8Rg==,type:str]
    SECRET_AUTHENTIK_POSTGRES_PASSWORD: ENC[AES256_GCM,data:h8NuMyQoWUmyzZlVqAeylsEi/Z43,iv:lfZSm28yeaIECJPBXjj6Xf2yJSW1FUi7Jm0E2QnUqkU=,tag:Cex+b6sXDMdXkKe3hvIzkA==,type:str]
    SECRET_AUTHENTIK_REDIS_PASSWORD: ENC[AES256_GCM,data:crFol1LT2PWhovrgzK2orL+Q,iv:D8BgOssg1NGBGsyu87swkv23l8fi/+Zc7VLEbMQyDzg=,tag:geNmiIf+TyaHHlbYZw38MA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pqmv9umk70z2xyv8vvlma070d9rzr02j3ye8gjyv64ddf0sfwccspwsj8d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwWEliaXFqcVY3RmZzUmNC
            b25ja25tSU1TbkpmUFV2eGhSKzdWV0FJUndrCnluc21XK2wwa3lDK0ZzWGtlSWlB
            YXR1MEYyNklBVUcvR0pxbzRtU2pIblkKLS0tIENDOUtRc0QzUGxSK20vRHZJcWts
            MVZLUUJRZ3J1MWFDMnJjMkN3S2F6VkUKa/Op5w/CRSSGvOy5DiPu+4O0ZOxFe5WH
            HxxcmsL5vQAoNp3jgjs1ZA32HQkzgQGtCVwBJC82t6U1nFvVnGOz/g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-04T06:18:38Z"
    mac: ENC[AES256_GCM,data:u1mpInUzVtmE2pvFdlVdCD4/7OIAmCDAtbopIJxaKheLyelbip2UH1biU7VY14NtfI7Sw9XdN0Ip7FLuzRAnSsamp9Gsf9nPFrIb29285X+JxM9+2aeq08FbYzXh3h2IuGaY9VtrvHr579AdJHeWocFogkwX49JPasfY0rSvR/I=,iv:wiyi/o2zS6cVBsIeHsn54gO89zwY03rLy1ywbMG8WR0=,tag:TdhL7UtDfkb5zaOyXCX6lQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
