apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:yjuook7gukXnUKRtKbE=,iv:TftPsavoTaWOKd9uDLdLVtvZmwKkPjjs5a1B0QZrTiY=,tag:ZSjFqE70SewCYoQJaMGFJg==,type:str]
    SECRET_PASSWORD: ENC[AES256_GCM,data:3JBmVlKlzWeB,iv:nmWwnzLNGlJvusyEbq7UIcUfCS6UG6P8eEisumLE3oY=,tag:MNZLYT7MDbuRd8zYpNUAQQ==,type:str]
    LOCAL_DOMAIN: ENC[AES256_GCM,data:wMPFiRfk0mJaYalqrT/Ylz4frg==,iv:GSTU0nzyXcxqEG79iLW1k6waT2443CnDebrlG81THU8=,tag:nUJmWEQjxxBFenijvHA6sQ==,type:str]
    GATEWAY_IP: ENC[AES256_GCM,data:O+jnnfQXaLnMbvo=,iv:ON4JuY0q8fv6R0AWNhJHQGHjtnm1UN+cUkBo76EY1KI=,tag:3EJFhI4vVY1orCTugMzEVg==,type:str]
    NAS1_ADDR: ENC[AES256_GCM,data:izyvEq0xYSDKMD1Yrw==,iv:GufCtBtBuHEMfW0Kf4BZGGMyEAjEEKWnOUGkujS/08c=,tag:QHzDLWG5fvkcqgL5+vrc4A==,type:str]
    NAS2_ADDR: ENC[AES256_GCM,data:dcUlRyO0+C55jdk+VQ==,iv:7rDPKJ4l5xJ4g0znwAbkDpDwkvxuC9l9/xgKGhUb74o=,tag:ljK38Ps0LV8dbey4PePCCQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kmn982kderhq3468sre0cq9y93qmw4m4wk9eh5288a0reaa4xsrqpf0s9x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaSFVjZ2RUN0J0RHhHbXpz
            Nk9YUGthZUxtZWNYeHJnV1hWT09vM1F0RkNFCkpBUGJjaEZTSngrQnNGeE5xcGVa
            Ui9mNU5uNVlnZGRuWEtmc0lkVnBDYncKLS0tIGtPS01YbEdqRVYxTEdoMVE5R25N
            bk1XNVF1My9Sa0hLU0ZSN1puZWIwM2sK4PfdM8DICFTw5HdExYlZS7HTwXtaiEz6
            uO38YBY2S9g71iWzFQ1mUnWP+BZb9FVostiVUQUKlzPVXtP1C3zs6w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-08T20:30:06Z"
    mac: ENC[AES256_GCM,data:llknYPisWSvVfbYAqIQnFMb2BuMoJvf5h2FnCwxkjvgdMZvdE0l1FC9AZTZs5J6UqOSlPXjyciY0ddHh9LMhNVLzAvXmLvpWByRnC+O+DqLPlMeBvAlARrcsyfPGVD+oX/YoPGOxBaEJTAM7ajHndUUlJGJq3fEPdsbtFPaDLSY=,iv:AuDH7qVztJcMrXkeWQrL6su5RIphbdVERMaPiy8oIeo=,tag:u8xOZvOHO+uzQJ7YHewADA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
