apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EMAIL: ENC[AES256_GCM,data:rGR6eWVLLcm+PtV3Je3XawnN,iv:jqY5WR0Ea/pg2cEexbTO3/o0toK45msiBnz0IXVi60M=,tag:apcZGpHF7xE5/uNEbHns8g==,type:str]
    IPINFO_TOKEN: ENC[AES256_GCM,data:QxxIEra8yP4KbediP/8=,iv:vPPb9IWjQmSfw10fXsb5uNvLos0/kgQRBNiuOcOmFEA=,tag:HHjAwPeOf/lEmSXbYd+SVQ==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:vKmPoLUUvKdYWB5EJkY=,iv:SW6SIg2hiqDZBLv3z4i2cEBEwy+VGP6IvazbxJadSd0=,tag:IfOviqD7oy78sOLDgAfdpA==,type:str]
    INTERNAL_DOMAIN: ENC[AES256_GCM,data:1mkBa0Ey7+2A2ZqqVOwmvB2yWA==,iv:4j64+Y8If3arGLrE7ctrPs74DNj+gF6HpCQWhFKD+8g=,tag:ZrSoAUXnl77YVq98VOrmdw==,type:str]
    VALHEIM_SERVER: ENC[AES256_GCM,data:pdIsCiTLsObGuZrR,iv:856QMIJ+EjawBIb4uZjy8V5IV9S7XGriYdizojVC8LE=,tag:1nUO+9jcEF8d3rq/7xN+YQ==,type:str]
    VALHEIM_WORLD: ENC[AES256_GCM,data:74eHG2fIXJXxswGO,iv:uHxgir2BxZisqxSJrM8jjY3qL6BheAdY6LlgOxn5yuI=,tag:KMF0ufXTaoVRSYGgMhoDJw==,type:str]
    VALHEIM_PASS: ENC[AES256_GCM,data:B5cflKcRk3A=,iv:ULAp9RzcctNWK39bmU2hGoZZiMrWwBSmVnJ7jS2jxQs=,tag:XmBbC6bp8xv7MxKzicDEuA==,type:str]
    SUPERVISOR_PASS: ENC[AES256_GCM,data:1/G7pvvbb35h,iv:rNsS7qv9UKUl+sv+Ey3FplNoESdm36MGqHaWf6CYv8E=,tag:mXlRbq6RoDYeV/CgChZC/g==,type:str]
    LOKI_MINIO_ACCESS_KEY: ENC[AES256_GCM,data:YZfSTwB04JLxIIYoLw==,iv:5DNyqGNefjEZoKu4zO4Z3I55ZR4cFtpJJLaZB2rQ/Ig=,tag:dCxFNef6KqlvHNvzy0SLsA==,type:str]
    LOKI_MINIO_SECRET_KEY: ENC[AES256_GCM,data:78J9GlZddrzz/Ue8QkmQDUh/deLdGRZh,iv:Tmpwz60VXpdViEunJI4aK98QSKtAexZw3BE2RtFeLAI=,tag:k/RMe0EK3mVdtYkz7+o80A==,type:str]
    SECRET_PASSWORD: ENC[AES256_GCM,data:NaV7wTxpj1vB,iv:48x+UL5QhmTZLBKU+WBdYoJxFXJ6EOfM8opWgqmns9A=,tag:qgYCkuQn+Z3JB3rmZas7JQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pqmv9umk70z2xyv8vvlma070d9rzr02j3ye8gjyv64ddf0sfwccspwsj8d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIeDc3QjRwODMySDQ1eDI4
            Nzl6aHpZYmorUXdYUlpNcHI2UTdiejJ4N2prCmFlZ1d1eDY3Z0o2NzZ5dXVTOXc0
            VVpZR3VZaW4zTGdkaDVwNTZ3K3lHdmcKLS0tIGxQczZRZ3cyM1ZSdEhUc3VWOHlz
            ZnFCZFQrT3IxRnBRclJKTVBvaDVTV2cKum2+2CWOifMtHh2q541QHcJvVZajUbdf
            jedikI3+Q+3SpW7Q+lJIz1UmitUudLCDvTwEBKnPUrPCs/jyZRjyow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-25T16:17:28Z"
    mac: ENC[AES256_GCM,data:5l3w/Sz71jtVD+FNiXr+bHJKn4HtysSl9wRPGrA2McBoC+Jz7bIE6VQfyrRyYQN9ekXAFzuIjQkJysZ1fd19JGR9I+zAllcBBMgMvUzdzO97CqP9Gwbxy7of1rCpt1zAhxzhut0IlUHiW+sWdwj5m5cBwAp4xo7i4ipc41T9cNA=,iv:4Mu76S6Wlu63+2zsU07nbOZwcsVjQaqvXZFPKWwXio4=,tag:GWuoS11vcBV/2ALKZGmP+A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
