apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EMAIL: ENC[AES256_GCM,data:yUQLJuZS4BsTR73M0cep4vYd,iv:lS8z12t4w2qoAlVlprJEyS1PAJUTQA+XrgijoRnxePQ=,tag:0dgbOCFNq+XrfZxIDsQqzA==,type:str]
    ACCESSTOKEN: ENC[AES256_GCM,data:OV7huzXEIUtcJ5D4/0o=,iv:CfrslBoxKmJzsiSTf7FOQ1bMy9ZmV+PWTAFOqFCZLiQ=,tag:9wTWzlQPVcri/ruaBcsgCg==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:YokdPzc2sWTLLLGlkDU=,iv:SNKpkHCG18XOBAsTnNsK6WBE0a5TKcVNcFZBGP5g0qw=,tag:YCJdRLwfhDOifYRvLoLqsg==,type:str]
    INTERNAL_DOMAIN: ENC[AES256_GCM,data:8wvwsiB2a/GsOnIsO89lV5k+Cw==,iv:Nt5vml2cOklPaIt94bnAR94XNoGz1lZwlCo9utW42Xo=,tag:R5d1B3/F9nNOJEpTkoyYhA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pqmv9umk70z2xyv8vvlma070d9rzr02j3ye8gjyv64ddf0sfwccspwsj8d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBraGMvNllZY3hqamNkakNi
            Q3EwRW9PanpmcTlNVDg4ckxkSTlrdHpUdVQ4Cm1KSW1SR3hzNzkvTnY2UWVYSDhW
            cFUzWHdZcnFEMW1rWVZaS29kV2JuWXMKLS0tIDJrYVE2dzlTRlJhcmlONmpvYkFW
            bTN5S3Jyem5zQTZVZVI5YkZubEpMV1EKcscuuEJi56lb1wuXdv/OrYee8S3JlXJh
            3BPhNfbo6qUEFUBYojcq5mFrNlKYlPR5suA5L/m5K3lvKYD7rEz/jg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-19T17:09:45Z"
    mac: ENC[AES256_GCM,data:U2wq8QIBARTnPAcPIr1Jdci3DDvqiVBj04tQywsMWc+iVlB8NA046FcawkQ2CV22fy3HfV3z0CCs68k0oFCPZ7ycHzzcwqYnhWNpPmCj6A8jni1snf3AcdVLG6yzXIbJrTyKUKg3lMAJo2jO3P1ECm7vtzN0B0xb2dt+hMeIUfc=,iv:xMTTIHJM3z2ac+bd0pXSEO2MV/DN6WmuNATh7BsXTQ0=,tag:UmeB9gzgrrFdwN/ypPiKyw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
