apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EMAIL: ENC[AES256_GCM,data:RFJQ+WcCA++VEc4299Iz6cdh,iv:izvc3eZ80P31x8EChrlzBPug4l7VRnKbyN5S2OR32f8=,tag:z8/Nki/bcbOWVMXaj37B5w==,type:str]
    IPINFO_TOKEN: ENC[AES256_GCM,data:d6mN/tedxKmk5pCA/oM=,iv:nxQmTPR4GPjisL63PVomnoK4nYBT9FIsDI+Ya6Qu0JI=,tag:7xIsKchxMQDlxwS3XZdKfA==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:DdOr5Zfi5fIQZ49kqMQ=,iv:LmJj7dhWneQkYJ06NTPSFfd43jgx/isLclPYTR7F3bk=,tag:2F14lmz27w7XE52lP17vlw==,type:str]
    INTERNAL_DOMAIN: ENC[AES256_GCM,data:hnFr2/pCs/Yh0WOWgOY7V+lqRQ==,iv:qXU2yS3t9GKVKJM+RvhR11b8qMZLjjws55XKcIulI3Y=,tag:lZFRhfxjTMxyng1UDdeD4w==,type:str]
    VALHEIM_SERVER: ENC[AES256_GCM,data:MBjBTAchMwXNQ1CN,iv:Ztnh/nUhF9PAxT63FZ98diG2fYUF4I13xW5Cm3vuHS4=,tag:ufwCOFWGYvd9efQv0sB+xA==,type:str]
    VALHEIM_WORLD: ENC[AES256_GCM,data:joRuMDrdCvL7ZQkZ,iv:8VnpOE3+kwww2LF0hLUm5JEEyAcD1ybpgf6/dyIFh0o=,tag:/9TZjW79dPUwbiG37AF+6g==,type:str]
    VALHEIM_PASS: ENC[AES256_GCM,data:3hmooPKnbbg=,iv:xrPbyEEPL7giVevyDEYTUsF3di3TirWvSMMsUw+kyrA=,tag:1+ETMExTPa5t4XlIAaMV1w==,type:str]
    SUPERVISOR_PASS: ENC[AES256_GCM,data:nZj6M2q9zIH6,iv:FbX5aBYLNyfvvE7z6AAdbhRP/qiH+RfXNkz8pqPjgoM=,tag:2t9yEzZYuRIF6fN2HvW8Zw==,type:str]
    LOKI_MINIO_ACCESS_KEY: ENC[AES256_GCM,data:UiuMakhv8I0XzAtFQA==,iv:yXSABE/0/KDdRvGfpEzm95PrhVrXrrlB872gePOPRJ4=,tag:11SsWvO5cLCKx2wbeC76eQ==,type:str]
    LOKI_MINIO_SECRET_KEY: ENC[AES256_GCM,data:Hlrm+2g68dRKjeqdIWiEV0LdY7MpoSDf,iv:Y7+cVp9JvNNtEIbGlU9+NtF/KwEFiFf6LlLQo14Us1g=,tag:UsqW3TpZu49H6EsfNylRHw==,type:str]
    SECRET_PASSWORD: ENC[AES256_GCM,data:W+lRrqsMvOUl,iv:tKehtygwk7aHbgghYrCdKEES69ZnGZ8qCw42r+kCt/Y=,tag:foTS/vDT+2l0luSNMptnzA==,type:str]
    SECRET_POSTGRESQL_KUBE_POSTGRES_PASSWORD: ENC[AES256_GCM,data:qLlDL3IHvnuw,iv:rYyHztPoGkyfPdl0ub8UNEwgjKQt9gwraq6qh2BbScY=,tag:5rsyCN4DstgVgPncinyFqQ==,type:str]
    SECRET_REDIS_PASSWORD: ENC[AES256_GCM,data:FY6XxXAkvJKW,iv:rIQSV8Ri8KRG1fCXr1wQh0t1UeqRxrz6tkYfYsYPkp0=,tag:hOQ/yL1b1NOgU1OxvDJdng==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pqmv9umk70z2xyv8vvlma070d9rzr02j3ye8gjyv64ddf0sfwccspwsj8d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmWUFUUlcrOWZWbmNCTitP
            TCthQ3YzQ2JtRHZ2L2JRbkZsMzExejNIdVRrClloektBcmxQRzZRd2tNTUpGeXQz
            dFZCWUNxdjNMQU1UVVVkMWdUZmVwRjgKLS0tIHNIOGJiYk5PRG9kM2M1d0cxWEVu
            SXRKaHJmUEZiMHpPNUNpSTFXS2lhaW8KfGIKd8Y4gspqDoPOvEmbHj7meHrKZfKV
            Nr0+bG0urHzqKy7bpWC6wngf9+mBWEsiVTx8XTK6wAEZt+Tn6JqboQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-27T14:16:45Z"
    mac: ENC[AES256_GCM,data:vSnAxbL8LlOHZpbvdBt+pa+Qj3fBYFWiVKpJSTbLGe0XkIorVMFLmDT44/cceFPLke+2kFJQOl3N80NBeoiUCCSDxy73T2n07JEr2GJogEXjJ85E1ByLS9/po+rwNDQx4s1ogAU2e8tUXSjpriaVCyn3DWgr7nhqpMgoBrjWeXU=,iv:0otHX4eRCyKQWClE6qiqR5kyEeektoYKtwVh2Q547ZQ=,tag:B06v4mo37olLfUaCns0Rkw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
