apiVersion: v1
kind: Secret
metadata:
    name: metadataConnection
    namespace: dev
data: ENC[AES256_GCM,data:AJMEc/r1yYsPrEEnkgfbreSchBe7MM3sWSxrgBZxNf3FKrk5mFfiozYmN60ThgF9evyr8hK2K+h/AaKYldWQBdcTqfi1ChAeYmvc9CspIlFcSPLCAsJ7LgurCEhoPyQ=,iv:emZe4QsEblOmOg1VFvwWoBtObQsZiGcvNpUr19POq58=,tag:9Iw7CugD3d1tSo9gZf/DGw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pqmv9umk70z2xyv8vvlma070d9rzr02j3ye8gjyv64ddf0sfwccspwsj8d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWbEdEWTVEMklvUVc2NHR1
            OUR0c25LZFlUeERPSDRTRDNsVHhTd2hNdmc4CndKUnBEaS9VZW12eG5PcXNVZFZC
            N1dHVXBHdmNBdnZRb2dnVlNHcXBQUHcKLS0tIGp1WGx1aFYrRWg0T0dDekRQb3dX
            eHIyZUM2NGorL21mZmNJYktEaCtCSncK1YjVifSnyaA5spa/qqoQOLiGBKJ4qAPq
            ZSFNOfpXME20oihNZdkyIC63a4BXP6HRn3y5Z2A7DmHhcwPToTy4qA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-16T19:41:17Z"
    mac: ENC[AES256_GCM,data:7ybthIwu8euj5YBwNF8QAaoYhlxRciUzfeKdL9udI96ly0E1p8cUTfuh98x+BikMsjNIoHwD+vCRTVm0HMRNSb6qKfZRUptJKUrDHMyTgcHFqKdIqD08QOp69vhUrcKi8WjA4URnvWu4sgWvJyvHmZwNveM/Gt5VmaIB99A7tVA=,iv:EFlnkKfCRUmIXC5EO4mHl61c1+TAjN94XmMMlEs7swo=,tag:FByTZ/xsK4uowOuP2tKikA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
