apiVersion: v1
kind: Secret
metadata:
    name: metadataConnection
    namespace: dev
stringData:
    user: ENC[AES256_GCM,data:XfOPmRWsAg8=,iv:BgHxCrtm1OW5MiK6rln9mkKu41wL1aqjuVtbBQxyFzs=,tag:ioIIoGzppS5qLnw7NpBXAQ==,type:str]
    pass: ENC[AES256_GCM,data:V3PEvAbPwwQ=,iv:h4jCbKnjnMeLXi6BuwmlyeUgc+v5p01UmAcVeRu/GPI=,tag:QwVQYkoS9MlQQnHQLnU8Mg==,type:str]
    protocol: ENC[AES256_GCM,data:FZTHdwa/CvaqnQ==,iv:OjkeVOkVnImcPGZCX8yRNoMOAMhyEcSAlakJrNXUTxM=,tag:MjatXSfbEgQITlLCXAyjxA==,type:str]
    host: ""
    port: ENC[AES256_GCM,data:Zr5KXg==,iv:ZOc6qqsMm/P9rapmBfEGm/EacJHj2q/8IxbuXvkwRcQ=,tag:w3bPtQr8plRNciCLd9bQtg==,type:int]
    db: ENC[AES256_GCM,data:uTgeMQftL/E=,iv:3vzpPmZN6tSuuOTI8tKY32ddqyC/idJI5FcJ3Wn2I2U=,tag:2G48gliOhgjvExrylcPg3A==,type:str]
    sslmode: ENC[AES256_GCM,data:pFPrxthZNg==,iv:RHeCjMSeYmJkD/DeCeVBjJDhBVswIOdmU7jJWcxWxLI=,tag:HQaCSqvwIjoq094j9XFSlQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pqmv9umk70z2xyv8vvlma070d9rzr02j3ye8gjyv64ddf0sfwccspwsj8d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYMjcrbEM2Mjk2WUM0UC8x
            VGtaOHhzTnZYUWlvRU9RQmgwOTd6U0pmWkRFClBsYlFoZisxb3dJSEhuN2MveU5w
            aGZQYTdvdFZuTXlObVlRcmlqTXJqdzAKLS0tIFBjK1JES2tQN0dra2NyZWlpeE5S
            cWdUZmRqeThSK0F6MXpBYVoyb0ZRblUKVPItcD2HBhCnrkTTiICQfhdApgQIFV9f
            s3Qg8GZupno2NCfLZh8gi6ISMVWKf58B54qY0D4PJtqIFypV3QrAnA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-16T18:40:00Z"
    mac: ENC[AES256_GCM,data:jBdBAXrApioYBellIYw4FRnEMvdKQtYZHhIEQX/6IfTY7VKOihl/cXLLdjFFWUaHfh7aTy8Ye02mU6cb7spCU7FIPBYd5GigCR/+vDIiqougKlpSKYdTund0+N9g8VYWo1Blqp8qjuKvMfB7hUW8I2O62f90gwdMkDXa46IKy+A=,iv:rLIxyCnR3CbCP5DCFoVeQgXn8R+ULhPS1l3hAxaU20c=,tag:6PJJAQSZ1UWWII3Eu02r6Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
