---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dags-v1
  namespace: dev
  labels:
spec:
  accessModes:
    - ReadWriteONCE
  resources:
    requests:
      storage: 100Gi
  storageClassName: longhorn



   gitSync:
    enabled: false

    # git repo clone url
    # ssh examples ssh://git@github.com/apache/airflow.git
    # git@github.com:apache/airflow.git
    # https example: https://github.com/apache/airflow.git
    
    repo: ssh//no1here0003@github.com/no1here0003/home-cluster.git
    branch: master
    rev: HEAD
    depth: 1
    
    # the number of consecutive failures allowed before aborting
    maxFailures: 0
    # subpath within the repo where dags are located
    # should be "" if dags are at repo root
    subPath: "test/dags"
    credentialsSecret: airflow-git
    
  logs:
    persistence: 
      enabled: true
      size: 10G