---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: airflow
  namespace: dev
spec:
  interval: 5m
  chart:
    spec:
      chart: airflow
      version: 3.10.2
      sourceRef:
        kind: HelmRepository
        name: airflow-charts
        namespace: flux-system
      interval: 5m

  values:
    airflow:
      ## configs for the docker image of the web/scheduler/worker
      ##
      image:
        repository: apache/airflow
        tag: 1.10.12-python3.6
        ## values: Always or IfNotPresent
        pullPolicy: IfNotPresent
        pullSecret: ""

      executor: CeleryExecutor

      extraEnv:
        - name: AIRFLOW__CORE__FERNET_KEY
          valueFrom:
            secretKeyRef:
              name: airflow
              key: fernetKey
    
      extraPipPackages:
        - "airflow-exporter==1.3.1"

      extraVolumes:
        - name: synchronised-dags
          emptyDir: {}

    scheduler:
      resources:
        requests:
          cpu: "1000m"
          memory: "1G"
    
    web:
      resources:
        requests:
          cpu: "500m"
          memory: "1Gi"

      baseURL: airflow.192.168.2.50.nip.io

      secretsDir: /var/airflow/secrets
    
    workers:
      enabled: true

      celery:
        instances: 16


    flower:
      enabled: true

    logs:
      path: /opt/airflow/logs

      presistence:
        enabled: true
        existingClaim: "airflow-logs-v1"
        storageClass: longhorn
        accessMode: ReadWriteMany
        size: 100G

    dags:
      path: /opt/airflow/dags

      persistence:
        enabled: true
        existingClaim: "dags-v1"
        storageClass: longhorn
        accessMode: ReadOnlyMany
        size: 10G

      git:
        url: "https://github.com/no1here0003.git"
        ref: master
        secret: airflow-ssh
        sshKeyscan: true
        privateKeyName: id_rsa
        repoHost: "github.com"
        repoPort: 22

        gitSync:
          enabled: true
          image:
            repository: alpine/git
            tag: latest
            ## values: Always or IfNotPresent
            pullPolicy: Always
            ## the git sync interval in seconds
            ##
        r efreshTime: 60

    ingress:
      enabled: true
      web:
        annotations:
          kubernetes.io/ingress.class: nginx
        path: "/"
        host: "airflow.192.168.2.50.nip.io"
        tls:
          enabled: true
          secretname: airflow-internal-tls
        
      flower:
        annotations:
          kubernetes.io/ingress.class: nginx
          path: "/"
          host: "flower.192.168.2.50.nip.io"


      postgresql:
        enabled: true
        postgresqlDatabase: airflow
        postgresqlUsername: postgres
        postgresql-password: airflow

        existingSecret: airlow
        existingSecretKey: "postgresql-password"

        persistence: 
          enabled: true
          storgabeClass: longhorn
          accessModes:
            - ReadWriteOnce
          size: 100G



