# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: null
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pqmv9umk70z2xyv8vvlma070d9rzr02j3ye8gjyv64ddf0sfwccspwsj8d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtd0cvMjR5akJpbCthaDF0
            V0tFZDNCTWRBOWFCNVVRUUUrTERwOFhnNVU4CkszUXVSSGVzekpKWXRlYzh4UzI4
            ZUUzenJ2U3kxOTh6Rmc3Zk44K2h3czAKLS0tIHJEYTQ3Z20vWVJEWDZPVitXQ2wy
            R09nMTZpbC9xZHVoMDkrVk5KbjlRVncKij11q0luBsUy0yGT6DylflOoZ2VUP/kT
            SUQelVfdSl9hVSuVl50Z9ZYo85QaaN/xYALF4autDO0zAsFw2wY5fQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-16T02:31:47Z"
    mac: ENC[AES256_GCM,data:9GoswBtcn92x/aNMbL97UeyvAR6cLgx1lzsJP376bR+u+NbM4m4m1fv63263ZZVD4ZYwd2QXyKTefEIRt6xfnWdkPqvzpSNYkFbEINZWvXhWMDU2jJspx511WX4BRqEHU4yZKqy9914kvk7sIuOSteFji0J3AcxMGkRgeYoIxOw=,iv:1IdVfniVJNw8pefueVhSkYQY7P6h1Y251vEHuSz1jA8=,tag:qUejm1AUtoqqun4dFC2JqQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
