# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: null
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pqmv9umk70z2xyv8vvlma070d9rzr02j3ye8gjyv64ddf0sfwccspwsj8d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFWkNKTWwrbnFsYjIrRjNR
            Q21ndHFQbU1IZ0R4NlZCS2FiSDMyTUNpODBrCmRWZlQvaklIbFNJRm5BcjhVQXFa
            bjRidzRLR2FXRFpseFR1RlpHZk5yS0kKLS0tIEdHRkIyS000UVhtMXVldFNyN1JH
            d2t4UEovUkRPbFZzVUxxK0lQcEd3bWcKbwmLez878S0VS7lwpSIs0glAUBGnhgCl
            lN98rHlF9d/ZNoeySlHWPneyRTH6aMXQnGEvZ0lftJCsOL7ZFUtUkg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-31T22:34:31Z"
    mac: ENC[AES256_GCM,data:KvYlrZt9aU3SNHKpDjcI1HNW/yMhwZehwx1gHDChzs0vzNvHU4qqKMIsmoGgZ9keJs0/ahKremCkENAnTxNlC7ckNIm5fyG5ZR9b0AvZQ4cAcxvIpyOb+7janjYDsGXN6kzXX/hVR2ivd3Shag6P412aw+xfGYUF6jhibJ4JQno=,iv:9mpOJM8I2QQgv0/YHV6OXqA8qYW/LdfSf5voMpyW64Y=,tag:fLazBdVbZEatjVSMRhkh9Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
