---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault
  namespace: hashicorp
spec:
  interval: 5m
  chart:
    spec:
      chart: vault
      version: 0.18.0
      sourceRef:
        kind: HelmRepository
        name: hashicorp-charts
        namespace: flux-system
      interval: 5m

  values:

    server:
      enabled: true
      image:
        repository: "hashicorp/vault"
        tag: "1.9.2"
        # Overrides the default Image Pull Policy
        pullPolicy: IfNotPresent

      ingress:
        enabled: true
        annotation: 
          kubernetes.io/ingress.class: nginx
        hosts:
          - host: vault.${INTERNAL_DOMAIN}
            paths:
              - /
        tls:
          - secretName: secret-vault-tls
          - hosts:
              - vault.${INTERNAL_DOMAIN}

      dataStorage:
        enabled: true
        size: 100Gi
        storageClass: "longhorn"

      resources:
        requests:
          memory: 256Mi
          cpu: 250m
      
      standalone:
        enabled: false

      extraVolumes:
        - type: secret
          name: kms-vault
          path: /vault/userconfig

      ha:
        enabled: true
        replicas: 3
        raft:
          enabled: true
          setNodeId: false
          config: |
            ui = true
            listener "tcp" {
              tls_disable = 1
              address = "[::]:8200"
              cluster_address = "[::]:8201"
            }
            storage "raft" {
              path = "/vault/data"
            }
            service_registration "kubernetes" {}

        config: |
          ui = true
          listener "tcp" {
            tls_disable = 1
            address = "[::]:8200"
            cluster_address = "[::]:8201"
          }
          storage "raft" {
            path = "/vault/data"
            address = "HOST_IP:8500"
          }
          service_registration "kubernetes" {}
      # Example configuration for using auto-unseal, using Google Cloud KMS. The
      # GKMS keys must already exist, and the cluster must have a service account
      # that is authorized to access GCP KMS.
      #seal "gcpckms" {
      #   project     = "vault-helm-dev-246514"
      #   region      = "global"
      #   key_ring    = "vault-helm-unseal-kr"
      #   crypto_key  = "vault-helm-unseal-key"
      #}

    csi:
      enabled: false

    ui:
      enabled: true