---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault
  namespace: hashicorp
spec:
  interval: 5m
  chart:
    spec:
      chart: vault
      version: 0.18.0
      sourceRef:
        kind: HelmRepository
        name: hashicorp-charts
        namespace: flux-system
      interval: 5m

  values:

    server:
      enabled: true
      image:
        repository: "hashicorp/vault"
        tag: "1.9.0"
        # Overrides the default Image Pull Policy
        pullPolicy: IfNotPresent

      readinessProbe:
        enabled: true
        path: "/v1/sys/health?sealedcode=204&uninitcode=204"
      livenessProbe:
        enabled: true
        path: "/v1/sys/health"
      initalDelaySeconds: 60

      ingress:
        enabled: true
        annotation: 
          kubernetes.io/ingress.class: nginx
        hosts:
          - host: vault.${INTERNAL_DOMAIN}
            paths:
              - /
        tls:
          - secretName: secret-vault-tls
          - hosts:
              - vault.${INTERNAL_DOMAIN}

      dataStorage:
        enabled: true
        storageClass: "longhorn"

      resources:
        requests:
          memory: 256Mi
          cpu: 250m
      
      standalone:
        enabled: false

      extraVolumes:
        - type: secret
          name: kms-vault
          path: /vault/userconfig

      ha:
        enabled: true
        replicas: 3
        raft:
          enabled: true
          setNodeId: true
          config: |
            ui = true
            listener "tcp" {
              tls_disable = 1
              address = "[::]:8200"
              cluster_address = "[::]:8201"
            }
            storage "raft" {
              path = "/vault/data"
            }
            seal "gcpckms" {
              project     = "kms-vault"
              region      = "global"
              key_ring    = "vault-unseal"
              crypto_key  = "vault-key"
            }
            service_registration "kubernetes" {}

    csi:
      enabled: false

    ui:
      enabled: true