---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mc-survival
  namespace: gaming
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://itzg.github.io/minecraft-server-charts/
      chart: minecraft
      sourceRef:
        kind: HelmRepository
        name: minecraft-server-charts
        namespace: flux-system
      interval: 5m
  values:
    image: itzg/minecraft-server
    imageTag: latest
    resources:
      requests:
        memory: 16384M
        cpu: 500m
    minecraftServer:
      eula: "TRUE"
      type: "VANILLA"
      pvp: "true"
      gameMode: survival
      motd: "Ethans Gaming Dungeon Survival Server"
      ops: "EthanDstroyr"
      memory: 16384M
      serviceType: LoadBalancer
      loadBalancerIP: "${MC_SURV_ADDR}"
    extraEnv:
      SERVER_NAME: EthanDstroyr
    persistence:
      dataDir:
        enabled: true
        existingClaim: mc-survival-v1
