---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ombi-config-v1
  namespace: downloads
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: longhorn