apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:UBv6sm85ogm20E1PcFfgLFSJ0ybeItVUhb7XL7UVBC1RQcCSvVrsoA==,iv:I4WkQO4LOhb2/uuNFxrHAi1M97v5MtTOJx40C99x7RQ=,tag:onmbl1fLG3zMu+RuAOdHWQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kmn982kderhq3468sre0cq9y93qmw4m4wk9eh5288a0reaa4xsrqpf0s9x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJczFqV0YyVVRic0hBSTJi
            M21zd1dmQlpLSUNKdHgzaTlZSXBXeGp6NjBrCjVvYjltZ3dPbUh4bVl0a3FIcnBB
            WSsxRUZqRDhpTkxEQlVhTDczdDB2cnMKLS0tIGFrUnVCTGFIMlF2VWx6S0h4eTMy
            M2cwdUlmb00yZ3F6RWhaZVJ0ajR0S28KkQYrwc2Eoi9PHG0XdwCTcCHsrvaBMltP
            jxNCeTJxF2BhooFptrQSq1AxpRbTIPqnY/C7UFk6J242KynpP4AWjQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-07T16:24:27Z"
    mac: ENC[AES256_GCM,data:279HZrMcANixmXqgt4oFPXFjaJVkT2UilvGkl+Sje7b0kTOrgd1TwBtKH/3/dcUdNKcURf0sstDinSdLOga4wIyFioJojC0LEy7UrMhEbMIf3DS6616+QhPFpHPcRQE/ghPxfZY3xPWuHoWzvBvbd9E+SdAymN7icCz+lsqim4s=,iv:IgAhQpzQ8RovrZ6WzzGRzc609q/FzaM10Ra7esChvIc=,tag:Ka0axOdtUwMY+YseutJs2Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
