---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant-postgresql
  namespace: home
  labels:
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: longhorn